/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

// Behavior specific product patches applied to release 710.
// This file is #included by hkbPatches_710.cpp.

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbCharacterDataCharacterControllerInfo", 0)
	HK_PATCH_MEMBER_ADDED_REAL("capsuleHeight", 1.700000f)
	HK_PATCH_MEMBER_ADDED_REAL("capsuleRadius", 0.400000f)
	HK_PATCH_MEMBER_ADDED_INT("collisionFilterInfo", 1)
	HK_PATCH_MEMBER_ADDED("characterControllerCinfo", TYPE_OBJECT, "hkpCharacterControllerCinfo", 0)
	HK_PATCH_DEPENDS("hkpCharacterControllerCinfo", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacterData", 4, "hkbCharacterData", 5)
	HK_PATCH_MEMBER_ADDED("characterControllerInfo", TYPE_STRUCT, "hkbCharacterDataCharacterControllerInfo", 0)
	HK_PATCH_DEPENDS("hkbCharacterDataCharacterControllerInfo", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbBehaviorGraphInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("nodeInternalStateInfos", TYPE_ARRAY_OBJECT, "hkbNodeInternalStateInfo", 0)
	HK_PATCH_MEMBER_ADDED("variableValueSet", TYPE_OBJECT, "hkbVariableValueSet", 0)
	HK_PATCH_DEPENDS("hkbNodeInternalStateInfo", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbVariableValueSet", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbNodeInternalStateInfo", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("syncInfo", TYPE_OBJECT, "hkbReferencedGeneratorSyncInfo", 0)
	HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("internalState", TYPE_OBJECT, "hkReferencedObject", 0)
	HK_PATCH_MEMBER_ADDED("nodeId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("hasActivateBeenCalled", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isModifierEnabled", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbGeneratorSyncInfo", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbClipGeneratorEcho", 0)
    HK_PATCH_MEMBER_ADDED("offsetLocalTime", TYPE_REAL, HK_NULL, 0)
    HK_PATCH_MEMBER_ADDED("weight", TYPE_REAL, HK_NULL, 0)
    HK_PATCH_MEMBER_ADDED("dwdt", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbStateMachineDelayedTransitionInfo", 0)
    HK_PATCH_MEMBER_ADDED("delayedTransition", TYPE_STRUCT, "hkbStateMachineProspectiveTransitionInfo", 0)
    HK_PATCH_MEMBER_ADDED("isDelayedTransitionReturnToPreviousState", TYPE_BYTE, HK_NULL, 0)
    HK_PATCH_MEMBER_ADDED("wasInAbutRangeLastFrame", TYPE_BYTE, HK_NULL, 0)
    HK_PATCH_DEPENDS("hkbStateMachineProspectiveTransitionInfo", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbStateMachineTransitionInfoReference", 0)
	HK_PATCH_MEMBER_ADDED("fromStateIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("transitionIndex", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbStateMachineProspectiveTransitionInfo", 1, "hkbStateMachineProspectiveTransitionInfo", 2)
	HK_PATCH_MEMBER_ADDED("transitionInfoReference", TYPE_STRUCT, "hkbStateMachineTransitionInfoReference", 0)
	HK_PATCH_MEMBER_ADDED("transitionInfoReferenceForTE", TYPE_STRUCT, "hkbStateMachineTransitionInfoReference", 0)
	HK_PATCH_MEMBER_ADDED("toStateId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbStateMachineTransitionInfoReference", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbStateMachineActiveTransitionInfo", 0, "hkbStateMachineActiveTransitionInfo", 1)
    HK_PATCH_MEMBER_REMOVED("transitionInfo", TYPE_OBJECT, "hkbStateMachineTransitionInfo", 0)
    HK_PATCH_MEMBER_REMOVED("transitionEffect", TYPE_OBJECT, "hkbTransitionEffect", 0)
    HK_PATCH_MEMBER_ADDED("transitionEffectInternalStateInfo", TYPE_OBJECT, "hkbNodeInternalStateInfo", 0)
    HK_PATCH_MEMBER_ADDED("transitionInfoReference", TYPE_STRUCT, "hkbStateMachineTransitionInfoReference", 0)
    HK_PATCH_MEMBER_ADDED("transitionInfoReferenceForTE", TYPE_STRUCT, "hkbStateMachineTransitionInfoReference", 0)
    HK_PATCH_DEPENDS("hkbNode", 1)
    HK_PATCH_DEPENDS("hkBaseObject", 0)
    HK_PATCH_DEPENDS("hkbGenerator", 0)
    HK_PATCH_DEPENDS("hkbTransitionEffect", 0)
    HK_PATCH_DEPENDS("hkbBindable", 0)
    HK_PATCH_DEPENDS("hkbStateMachineTransitionInfo", 1)
    HK_PATCH_DEPENDS("hkReferencedObject", 0)
    HK_PATCH_DEPENDS("hkbStateMachineTransitionInfoReference", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbBlenderGeneratorChildInternalState", 0)
	HK_PATCH_MEMBER_ADDED("isActive", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("syncNextFrame", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbEvaluateExpressionModifierInternalExpressionData", 0)
	HK_PATCH_MEMBER_ADDED("raisedEvent", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("wasTrueInPreviousFrame", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbGeneratorSyncInfoSyncPoint", 0)
	HK_PATCH_MEMBER_ADDED("id", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("time", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbGeneratorSyncInfo", 0)
	HK_PATCH_MEMBER_ADDED("syncPoints", TYPE_TUPLE_STRUCT, "hkbGeneratorSyncInfoSyncPoint", 8)
	HK_PATCH_MEMBER_ADDED("baseFrequency", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("localTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("playbackSpeed", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("numSyncPoints", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isCyclic", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isMirrored", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isAdditive", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbGeneratorSyncInfoSyncPoint", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbEventsFromRangeModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("wasActiveInPreviousFrame", TYPE_ARRAY_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbPositionRelativeSelectorGeneratorInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("entryPosition", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("entryForward", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("lastTargetPos", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("lastTargetRot", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("targetLinearDisp", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("targetAngularDisp", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("clipTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("currentGeneratorIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("usingBlendToFixPositionGenerator", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("doLeadInFixup", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbGeneratorTransitionEffectInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("timeInTransition", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("duration", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("effectiveBlendInDuration", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("effectiveBlendOutDuration", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("toGeneratorState", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("echoTransitionGenerator", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("echoToGenerator", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("justActivated", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("updateActiveNodes", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("stage", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbCombineTransformsModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("translationOut", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("rotationOut", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbDelayedModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("secondsElapsed", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isActive", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbDampingModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("dampedVector", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("vecErrorSum", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("vecPreviousError", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("dampedValue", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("errorSum", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("previousError", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbStateMachineInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("activeTransitions", TYPE_ARRAY_STRUCT, "hkbStateMachineActiveTransitionInfo", 0)
	HK_PATCH_MEMBER_ADDED("transitionFlags", TYPE_ARRAY_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("wildcardTransitionFlags", TYPE_ARRAY_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("delayedTransitions", TYPE_ARRAY_STRUCT, "hkbStateMachineDelayedTransitionInfo", 0)
	HK_PATCH_MEMBER_ADDED("timeInState", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("lastLocalTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("currentStateId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("previousStateId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("nextStartStateIndexOverride", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("stateOrTransitionChanged", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("echoNextUpdate", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("hasEventlessWildcardTransitions", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbStateMachineDelayedTransitionInfo", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbStateMachineActiveTransitionInfo", 1)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbTransformVectorModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("vectorOut", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbComputeRotationToTargetModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("rotationOut", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbClipGeneratorInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("extractedMotion", TYPE_VEC_12, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("echos", TYPE_ARRAY_STRUCT, "hkbClipGeneratorEcho", 0)
	HK_PATCH_MEMBER_ADDED("localTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("time", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("previousUserControlledTimeFraction", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("bufferSize", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("atEnd", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("ignoreStartTime", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pingPongBackward", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbClipGeneratorEcho", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbJigglerModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("currentVelocitiesWS", TYPE_ARRAY_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("currentPositions", TYPE_ARRAY_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("timeStep", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("initNextModify", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbSplinePathGeneratorInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("entryPosition", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("entryForward", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("exitPosition", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("exitForward", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("averageSpeed", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pathTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("curTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pathParam", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("currentGeneratorIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("doLeadInFixup", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("eventTriggered", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbMoveCharacterModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("timeSinceLastModify", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbLookAtModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("lookAtLastTargetWS", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("lookAtWeight", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isTargetInsideLimitCone", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbTimerModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("secondsElapsed", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbRotateCharacterModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("angle", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbComputeRotationFromAxisAngleModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("rotationOut", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbPoseMatchingGeneratorInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("currentMatch", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("bestMatch", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("timeSinceBetterMatch", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("error", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("resetCurrentMatchLocalTime", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbGetUpModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("timeSinceBegin", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("timeStep", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("initNextModify", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbEventDrivenModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("isActive", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbComputeDirectionModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("pointOut", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("groundAngleOut", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("upAngleOut", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("computedOutput", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbEvaluateExpressionModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("internalExpressionsData", TYPE_ARRAY_STRUCT, "hkbEvaluateExpressionModifierInternalExpressionData", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbEvaluateExpressionModifierInternalExpressionData", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbBlenderGeneratorInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("childrenInternalStates", TYPE_ARRAY_STRUCT, "hkbBlenderGeneratorChildInternalState", 0)
	HK_PATCH_MEMBER_ADDED("sortedChildren", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("endIntervalWeight", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("numActiveChildren", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("beginIntervalIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("endIntervalIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("initSync", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("doSubtractiveBlend", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbBlenderGeneratorChildInternalState", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbSequenceInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("nextSampleEvents", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("nextSampleReals", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("nextSampleBools", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("nextSampleInts", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("time", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isEnabled", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbDetectCloseToGroundModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("isCloseToGround", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbGetWorldFromModelModifierInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("translationOut", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("rotationOut", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbExtrapolatingTransitionEffectInternalState", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("fromGeneratorSyncInfo", TYPE_STRUCT, "hkbGeneratorSyncInfo", 0)
	HK_PATCH_MEMBER_ADDED("worldFromModel", TYPE_VEC_12, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("motion", TYPE_VEC_12, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pose", TYPE_ARRAY_VEC_12, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("additivePose", TYPE_ARRAY_VEC_12, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("toGeneratorDuration", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isFromGeneratorActive", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("gotPose", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("gotAdditivePose", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbGeneratorSyncInfo", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbCharacterSkinInfo", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("characterId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("skinIds", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbCharacterInfo", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("characterId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("instanceName", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("templateName", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("fullPathToProject", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("event", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbBehaviorInfo", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("characterId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("data", TYPE_OBJECT, "hkbBehaviorGraphData", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbBehaviorGraphData", 2)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbEventRaisedInfo", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("characterId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("eventName", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("raisedBySdk", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbRaiseEventCommand", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("characterId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("global", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("externalId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbCharacterControlCommand", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("characterId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("command", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbContext", 0, "hkbContext", 1)
	HK_PATCH_MEMBER_REMOVED("projectData", TYPE_OBJECT, "hkbProjectData", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbProjectData", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbStateMachine", 2, "hkbStateMachine", 3)
	HK_PATCH_FUNCTION(hkbStateMachine_2_to_3)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacterSetup", 1, "hkbCharacterSetup", 2)
	HK_PATCH_MEMBER_REMOVED("ragdollSkeleton", TYPE_OBJECT, "hkaSkeleton", 0)
	HK_PATCH_DEPENDS("hkaSkeleton", 2)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbLinkedSymbolInfo", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("eventNames", TYPE_ARRAY_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("variableNames", TYPE_ARRAY_CSTRING, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbFootIkControlsModifierLeg", 0)
    HK_PATCH_MEMBER_ADDED("groundPosition", TYPE_VEC_4, HK_NULL, 0)
    HK_PATCH_MEMBER_ADDED("ungroundedEvent", TYPE_STRUCT, "hkbEventProperty" , 0)
    HK_PATCH_MEMBER_ADDED_REAL("verticalError", 0.000000f)
    HK_PATCH_MEMBER_ADDED_BYTE("hitSomething", 0)
    HK_PATCH_MEMBER_ADDED_BYTE("isPlantedMS", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbFootIkControlsModifier", 0, "hkbFootIkControlsModifier", 1)
    HK_PATCH_MEMBER_ADDED("legs", TYPE_ARRAY_STRUCT, "hkbFootIkControlsModifierLeg", 0)
    HK_PATCH_DEPENDS("hkbFootIkControlsModifierLeg", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRagdollController", 3, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkReferencedObject", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("ragdollBlendOutTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("character", TYPE_OBJECT, "hkbCharacter", 0)
	HK_PATCH_MEMBER_REMOVED("ragdollInstance", TYPE_OBJECT, "hkaRagdollInstance", 0)
	HK_PATCH_MEMBER_REMOVED("ragdollPoseWS", TYPE_OBJECT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("firstGenerateAfterRagdollIsAddedToWorld", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("firstGenerateAfterRigidBodyControllerActive", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("autoAddRemoveRagdollToWorld", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("isEnabled", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("isPoweredControllerEnabled", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("isRigidBodyControllerEnabled", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("worldFromModelModeData", TYPE_STRUCT, "hkbWorldFromModelModeData", 0)
	HK_PATCH_MEMBER_REMOVED("useAsynchronousStepping", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbWorldFromModelModeData", 0)
	HK_PATCH_DEPENDS("hkbCharacter", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkaRagdollInstance", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacterData", 5, "hkbCharacterData", 6)
    HK_PATCH_MEMBER_ADDED("footIkDriverInfo", TYPE_OBJECT, "hkbFootIkDriverInfo", 0)
    HK_PATCH_DEPENDS("hkbFootIkDriverInfo", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbFootIkDriverInfo", 0)
    HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
    HK_PATCH_MEMBER_ADDED("legs", TYPE_ARRAY_STRUCT, "hkbFootIkDriverInfoLeg", 0)
    HK_PATCH_MEMBER_ADDED_REAL("raycastDistanceUp", 0.500000f)
    HK_PATCH_MEMBER_ADDED_REAL("raycastDistanceDown", 0.800000f)
    HK_PATCH_MEMBER_ADDED_REAL("originalGroundHeightMS", 0.000000f)
    HK_PATCH_MEMBER_ADDED_REAL("verticalOffset", 0.000000f)
    HK_PATCH_MEMBER_ADDED_INT("collisionFilterInfo", 3)
    HK_PATCH_MEMBER_ADDED_REAL("forwardAlignFraction", 1.000000f)
    HK_PATCH_MEMBER_ADDED_REAL("sidewaysAlignFraction", 1.000000f)
    HK_PATCH_MEMBER_ADDED_REAL("sidewaysSampleWidth", 0.000000f)
    HK_PATCH_MEMBER_ADDED_BYTE("lockFeetWhenPlanted", 0)
    HK_PATCH_MEMBER_ADDED_BYTE("useCharacterUpVector", 0)
    HK_PATCH_MEMBER_ADDED_BYTE("isQuadrupedNarrow", 0)
    HK_PATCH_DEPENDS("hkBaseObject", 0)
    HK_PATCH_DEPENDS("hkbFootIkDriverInfoLeg", 0)
    HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbFootIkDriverInfoLeg", 0)
    HK_PATCH_MEMBER_ADDED_VEC_4("kneeAxisLS", 0.000000f,0.000000f,1.000000f,0.000000f)
    HK_PATCH_MEMBER_ADDED_VEC_4("footEndLS", 0.000000f,0.000000f,0.000000f,0.000000f)
    HK_PATCH_MEMBER_ADDED_REAL("footPlantedAnkleHeightMS", 0.000000f)
    HK_PATCH_MEMBER_ADDED_REAL("footRaisedAnkleHeightMS", 0.500000f)
    HK_PATCH_MEMBER_ADDED_REAL("maxAnkleHeightMS", 0.700000f)
    HK_PATCH_MEMBER_ADDED_REAL("minAnkleHeightMS", -0.100000f)
    HK_PATCH_MEMBER_ADDED_REAL("maxKneeAngleDegrees", 180.000000f)
    HK_PATCH_MEMBER_ADDED_REAL("minKneeAngleDegrees", 0.000000f)
    HK_PATCH_MEMBER_ADDED_INT("hipIndex", -1)
    HK_PATCH_MEMBER_ADDED_INT("kneeIndex", -1)
    HK_PATCH_MEMBER_ADDED_INT("ankleIndex", -1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbSimpleCharacter", 3, "hkbSimpleCharacter", 4)
	HK_PATCH_MEMBER_REMOVED("ragdollController", TYPE_OBJECT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbRagdollController", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbActiveNodesInfo", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("characterId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("activeNodes", TYPE_ARRAY_STRUCT, "hkbActiveNodesInfoActiveNode", 0)
	HK_PATCH_MEMBER_ADDED("activeEventIds", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("activeVariableIds", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbActiveNodesInfoActiveNode", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbActiveNodesInfoActiveNode", 0)
	HK_PATCH_MEMBER_ADDED("nodeName", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("userData0", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("userData1", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("id", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("type", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("depth", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbBehaviorEventsInfo", 0)
    HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
    HK_PATCH_MEMBER_ADDED("characterId", TYPE_INT, HK_NULL, 0)
    HK_PATCH_MEMBER_ADDED("externalEventIds", TYPE_ARRAY_INT, HK_NULL, 0)
    HK_PATCH_DEPENDS("hkBaseObject", 0)
    HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacter", 0, "hkbCharacter", 1)
	HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbParticleSystemEventPayload", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbEventPayload")
	HK_PATCH_MEMBER_ADDED_BYTE("type", 1)
	HK_PATCH_MEMBER_ADDED_INT("emitBoneIndex", -1)
	HK_PATCH_MEMBER_ADDED_VEC_4("offset", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("direction", 0.000000f,0.000000f,1.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("speed", 1.000000f)
	HK_PATCH_MEMBER_ADDED_INT("numParticles", 100)
	HK_PATCH_DEPENDS("hkbEventPayload", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbPoweredRagdollControlData", 0, "hkbPoweredRagdollControlData", 1)
	HK_PATCH_MEMBER_ADDED("easeConstraintLimitsDuration", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbCameraShakeEventPayload", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbEventPayload")
	HK_PATCH_MEMBER_ADDED_REAL("amplitude", 1.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("halfLife", 1.000000f)
	HK_PATCH_DEPENDS("hkbEventPayload", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbSceneModifierList", 0, "hkbSceneModifierList", 1)
	HK_PATCH_FUNCTION(hkbSceneModifierList_0_to_1)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbSetNodePropertyCommand", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("characterId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("nodeName", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("propertyName", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("propertyValue", TYPE_STRUCT, "hkbVariableValue", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbVariableValue", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbProjectData", 0, "hkbProjectData", 1)
	HK_PATCH_MEMBER_ADDED_INT("defaultEventMode", 2)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbTwistModifier", 0, "hkbTwistModifier", 1)
	HK_PATCH_MEMBER_ADDED_INT("rotationAxisCoordinates", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbBehaviorGraph", 0, "hkbBehaviorGraph", 1)
	HK_PATCH_FUNCTION(hkbBehaviorGraph_0_to_1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbSimpleCharacter", 4, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkbCharacter", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("nearbyCharacters", TYPE_ARRAY_OBJECT, "hkbCharacter", 0)
	HK_PATCH_MEMBER_REMOVED("setup", TYPE_OBJECT, "hkbCharacterSetup", 0)
	HK_PATCH_MEMBER_REMOVED("worldFromModel", TYPE_OBJECT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("poseLocal", TYPE_OBJECT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("deleteWorldFromModel", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("deletePoseLocal", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("ragdollWorldFromModel", TYPE_VEC_12, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("behaviorGraph", TYPE_OBJECT, "hkbBehaviorGraph", 0)
	HK_PATCH_MEMBER_REMOVED("projectData", TYPE_OBJECT, "hkbProjectData", 0)
	HK_PATCH_DEPENDS("hkbNode", 1)
	HK_PATCH_DEPENDS("hkbProjectData", 1)
	HK_PATCH_DEPENDS("hkbCharacter", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbCharacterSetup", 2)
	HK_PATCH_DEPENDS("hkbGenerator", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbBehaviorGraph", 1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacter", 1, "hkbCharacter", 2)
	HK_PATCH_MEMBER_ADDED("nearbyCharacters", TYPE_ARRAY_OBJECT, "hkbCharacter", 0)
	HK_PATCH_MEMBER_ADDED("setup", TYPE_OBJECT, "hkbCharacterSetup", 0)
	HK_PATCH_MEMBER_ADDED("behaviorGraph", TYPE_OBJECT, "hkbBehaviorGraph", 0)
	HK_PATCH_MEMBER_ADDED("projectData", TYPE_OBJECT, "hkbProjectData", 0)
	HK_PATCH_MEMBER_ADDED("currentLod", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbNode", 1)
	HK_PATCH_DEPENDS("hkbCharacterSetup", 2)
	HK_PATCH_DEPENDS("hkbGenerator", 0)
	HK_PATCH_DEPENDS("hkbProjectData", 1)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkbBehaviorGraph", 1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbProjectStringData", 0, "hkbProjectStringData", 1)
	HK_PATCH_MEMBER_ADDED("fullPathToSource", TYPE_CSTRING, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbWorldEnums", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbSimulationControlCommand", 0)
    HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
    HK_PATCH_MEMBER_ADDED("command", TYPE_BYTE, HK_NULL, 0)
    HK_PATCH_DEPENDS("hkBaseObject", 0)
    HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbSimulationStateInfo", 0)
    HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
    HK_PATCH_MEMBER_ADDED("simulationState", TYPE_BYTE, HK_NULL, 0)
    HK_PATCH_DEPENDS("hkBaseObject", 0)
    HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbStateChooser", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbStateMachine", 3, "hkbStateMachine", 4)
	HK_PATCH_MEMBER_ADDED("startStateChooser", TYPE_OBJECT, "hkbStateChooser", 0)
	HK_PATCH_DEPENDS("hkbStateChooser", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbBallModifier", 0, HK_NULL, HK_CLASS_REMOVED)
    HK_PATCH_PARENT_SET("hkbModifier", HK_NULL)
    HK_PATCH_MEMBER_REMOVED("velocity", TYPE_VEC_4, HK_NULL, 0)
    HK_PATCH_MEMBER_REMOVED("applyForceEventId", TYPE_INT, HK_NULL, 0)
    HK_PATCH_MEMBER_REMOVED("applyForce", TYPE_BYTE, HK_NULL, 0)
    HK_PATCH_DEPENDS("hkbNode", 1)
    HK_PATCH_DEPENDS("hkBaseObject", 0)
    HK_PATCH_DEPENDS("hkbModifier", 0)
    HK_PATCH_DEPENDS("hkbBindable", 0)
    HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbSetLocalTimeOfClipGeneratorCommand", 0)
   HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
   HK_PATCH_MEMBER_ADDED("characterId", TYPE_INT, HK_NULL, 0)
   HK_PATCH_MEMBER_ADDED("localTime", TYPE_REAL, HK_NULL, 0)
   HK_PATCH_MEMBER_ADDED("nodeId", TYPE_INT, HK_NULL, 0)
   HK_PATCH_DEPENDS("hkBaseObject", 0)
   HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbPoweredRagdollControlData", 1, "hkbPoweredRagdollControlData", 2)
	HK_PATCH_MEMBER_REMOVED("easeConstraintLimitsDuration", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbCharacterControllerModifier", 0)
    HK_PATCH_PARENT_SET(HK_NULL, "hkbModifier")
    HK_PATCH_MEMBER_ADDED("controlData", TYPE_STRUCT, "hkbCharacterControllerControlData", 0)
    HK_PATCH_MEMBER_ADDED_VEC_4("initialVelocity", 0.000000f,0.000000f,0.000000f,0.000000f)
    HK_PATCH_MEMBER_ADDED("initialVelocityCoordinates", TYPE_INT, HK_NULL, 0)
    HK_PATCH_MEMBER_ADDED_INT("motionMode", 0)
    HK_PATCH_MEMBER_ADDED_BYTE("forceDownwardMomentum", 1)
    HK_PATCH_MEMBER_ADDED_BYTE("applyGravity", 1)
    HK_PATCH_MEMBER_ADDED_BYTE("setInitialVelocity", 0)
    HK_PATCH_MEMBER_ADDED_BYTE("isTouchingGround", 1)
    HK_PATCH_DEPENDS("hkbNode", 1)
    HK_PATCH_DEPENDS("hkbCharacterControllerControlData", 0)
    HK_PATCH_DEPENDS("hkBaseObject", 0)
    HK_PATCH_DEPENDS("hkbModifier", 0)
    HK_PATCH_DEPENDS("hkbBindable", 0)
    HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbCharacterControllerControlData", 0)
    HK_PATCH_MEMBER_ADDED_VEC_4("desiredVelocity", 0.000000f,0.000000f,0.000000f,0.000000f)
    HK_PATCH_MEMBER_ADDED_REAL("verticalGain", 1.000000f)
    HK_PATCH_MEMBER_ADDED_REAL("horizontalCatchUpGain", 1.000000f)
    HK_PATCH_MEMBER_ADDED_REAL("maxVerticalSeparation", 0.000000f)
    HK_PATCH_MEMBER_ADDED_REAL("maxHorizontalSeparation", 0.000000f)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbTestStateChooser", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbStateChooser")
	HK_PATCH_MEMBER_ADDED("int", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("real", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("string", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbStateChooser", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbStateMachineTransitionInfoReference", 0, "hkbStateMachineTransitionInfoReference", 1)
	HK_PATCH_MEMBER_ADDED_INT("stateMachineId", -1)
HK_PATCH_END()

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20130718)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
