/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

#include "Reflections/hkpRackAndPinionConstraintDataReflection.cpp"
#include "Reflections/hkpRagdollConstraintDataReflection.cpp"
#include "Reflections/hkpLimitedForceConstraintMotorReflection.cpp"
#include "Reflections/hkpParametricCurveReflection.cpp"
#include "Reflections/hkpLinearClearanceConstraintDataReflection.cpp"
#include "Reflections/hkpConstraintAtomReflection.cpp"
#include "Reflections/hkpRotationalConstraintDataReflection.cpp"
#include "Reflections/hkpCallbackConstraintMotorReflection.cpp"
#include "Reflections/hkpConstraintMotorReflection.cpp"
#include "Reflections/hkpBridgeConstraintAtomReflection.cpp"
#include "Reflections/hkpLinearParametricCurveReflection.cpp"
#include "Reflections/hkpStiffSpringConstraintDataReflection.cpp"
#include "Reflections/hkpHingeLimitsDataReflection.cpp"
#include "Reflections/hkpPrismaticConstraintDataReflection.cpp"
#include "Reflections/hkpHingeConstraintDataReflection.cpp"
#include "Reflections/hkpConstraintDataReflection.cpp"
#include "Reflections/hkpLimitedHingeConstraintDataReflection.cpp"
#include "Reflections/hkpBallAndSocketConstraintDataReflection.cpp"
#include "Reflections/hkpCogWheelConstraintDataReflection.cpp"
#include "Reflections/hkpSpringDamperConstraintMotorReflection.cpp"
#include "Reflections/hkpPulleyConstraintDataReflection.cpp"
#include "Reflections/hkpRagdollLimitsDataReflection.cpp"
#include "Reflections/hkpVelocityConstraintMotorReflection.cpp"
#include "Reflections/hkpDeformableFixedConstraintDataReflection.cpp"
#include "Reflections/hkpFixedConstraintDataReflection.cpp"
#include "Reflections/hkpPointToPlaneConstraintDataReflection.cpp"
#include "Reflections/hkpPointToPathConstraintDataReflection.cpp"
#include "Reflections/hkpWheelConstraintDataReflection.cpp"
#include "Reflections/hkpPositionConstraintMotorReflection.cpp"

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20130718)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
