/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

// Cloth specific product patches applied before release 660.
// This file is #included by hclPatches_Legacy.cpp

HK_PATCH_BEGIN("hclTransitionConstraintSetPerParticle", 0, "hclTransitionConstraintSetPerParticle", 1)
	HK_PATCH_MEMBER_ADDED("toAnimDelay", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("toSimDelay", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_REAL("toSimMaxDistance", 1.0f)
	HK_PATCH_FUNCTION(hclTransitionConstraintSetPerParticle_0_to_1)
	HK_PATCH_MEMBER_REMOVED("particleDelay", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSkinOperator", 0, "hclSkinOperator", 1)
	HK_PATCH_MEMBER_ADDED_INT("startVertex", 0)
	HK_PATCH_MEMBER_ADDED("endVertex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_FUNCTION(hclSkinOperator_0_to_1)
HK_PATCH_END()

HK_PATCH_BEGIN("hclTransitionConstraintSet", 0, "hclTransitionConstraintSet", 1)
	HK_PATCH_MEMBER_ADDED("toAnimPeriod", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("toAnimPlusDelayPeriod", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("toSimPeriod", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("toSimPlusDelayPeriod", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_FUNCTION(hclTransitionConstraintSet_0_to_1)
	HK_PATCH_MEMBER_REMOVED("transitionPeriod", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("transitionPlusDelayPeriod", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclScratchBufferDefinition", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hclBufferDefinition")
	HK_PATCH_MEMBER_ADDED_BYTE("storeNormals", 0)
	HK_PATCH_MEMBER_ADDED_BYTE("storeTangentsAndBiTangents", 0)
	HK_PATCH_MEMBER_ADDED("triangleIndices", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hclBufferDefinition", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclMeshMeshDeformOperator", 0, "hclMeshMeshDeformOperator", 1)
	HK_PATCH_MEMBER_ADDED_INT("startVertex", 0)
	HK_PATCH_MEMBER_ADDED("endVertex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_FUNCTION(hclMeshMeshDeformOperator_0_to_1)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSimClothSetupObjectPerInstanceCollidable", 0)
        HK_PATCH_MEMBER_ADDED("collidable", TYPE_OBJECT, "hclCollidable", 0)
        HK_PATCH_MEMBER_ADDED("collidingParticles", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclCollidable", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSimulationSetupMeshMapOptions", 0)
        HK_PATCH_MEMBER_ADDED("collapseVertices", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("collapseThreshold", TYPE_REAL, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("vertexSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSetupMeshSectionTriangle", 0)
        HK_PATCH_MEMBER_ADDED("indices", TYPE_TUPLE_INT, HK_NULL, 3)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSimulateSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclOperatorSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("simClothSetupObject", TYPE_OBJECT, "hclSimClothSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("numberOfSubsteps", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("numberOfSolveIterations", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("explicitConstraintOrder", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("constraintSetExecutionOrder", TYPE_ARRAY_OBJECT,"hclConstraintSetSetupObject", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclOperatorSetupObject", 0)
        HK_PATCH_DEPENDS("hclSimClothSetupObject", 0)
        HK_PATCH_DEPENDS("hclConstraintSetSetupObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

#if defined(HK_FEATURE_PRODUCT_CLOTH) && defined(HK_FEATURE_PRODUCT_ANIMATION)

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSkeletonTransformSetSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclTransformSetSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("skeleton", TYPE_OBJECT, "hkaSkeleton", 0)
        HK_PATCH_MEMBER_ADDED("worldFromModel", TYPE_VEC_16, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclTransformSetSetupObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hkaSkeleton", 0)
HK_PATCH_END()

#endif // HK_FEATURE_PRODUCT_CLOTH && HK_FEATURE_PRODUCT_ANIMATION

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclVertexCopySetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclOperatorSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("inputBufferSetupObject", TYPE_OBJECT, "hclBufferSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("outputBufferSetupObject", TYPE_OBJECT, "hclBufferSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("copyNormals", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclOperatorSetupObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclNamedTransformSetSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclTransformSetSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("skelName", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclTransformSetSetupObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBonePlanesSetupObjectGlobalPlane", 0)
        HK_PATCH_MEMBER_ADDED("transformName", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("particles", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("planeEquationBoneSpace", TYPE_VEC_4, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("allowedPenetration", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("stiffness", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclVertexFloatInput", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSimulationSetupMesh", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclSetupMesh")
        HK_PATCH_MEMBER_ADDED("originalMesh", TYPE_OBJECT, "hclSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("mergeOptions", TYPE_STRUCT, "hclSimulationSetupMeshMapOptions", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclSimulationSetupMeshMapOptions", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclStandardLinkSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclConstraintSetSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("simulationMesh", TYPE_OBJECT, "hclSimulationSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("vertexSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("stiffness", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclSimulationSetupMesh", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclConstraintSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBonePlanesSetupObjectPerParticleAngle", 0)
        HK_PATCH_MEMBER_ADDED("transformName", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("particlesMaxAngle", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("particlesMinAngle", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("originBoneSpace", TYPE_VEC_4, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("axisBoneSpace", TYPE_VEC_4, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("minAngle", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("maxAngle", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("stiffness", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclVertexFloatInput", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBonePlanesSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclConstraintSetSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("simulationMesh", TYPE_OBJECT, "hclSimulationSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("transformSetSetup", TYPE_OBJECT, "hclTransformSetSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("perParticlePlanes", TYPE_ARRAY_STRUCT, "hclBonePlanesSetupObjectPerParticlePlane", 0)
        HK_PATCH_MEMBER_ADDED("globalPlanes", TYPE_ARRAY_STRUCT, "hclBonePlanesSetupObjectGlobalPlane", 0)
        HK_PATCH_MEMBER_ADDED("perParticleAngle", TYPE_ARRAY_STRUCT, "hclBonePlanesSetupObjectPerParticleAngle", 0)
        HK_PATCH_DEPENDS("hclBonePlanesSetupObjectPerParticleAngle", 0)
        HK_PATCH_DEPENDS("hclConstraintSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclBonePlanesSetupObjectPerParticlePlane", 0)
        HK_PATCH_DEPENDS("hclBonePlanesSetupObjectGlobalPlane", 0)
        HK_PATCH_DEPENDS("hclSimulationSetupMesh", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclTransformSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclConstraintSetSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclStorageSetupMeshBone", 0)
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("boneFromSkin", TYPE_VEC_16, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSimClothSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("simulationMesh", TYPE_OBJECT, "hclSimulationSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("gravity", TYPE_VEC_4, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("globalDampingPerSecond", TYPE_REAL, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("enableMidPhase", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("doNormals", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("specifyDensity", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("vertexDensity", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("rescaleMass", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("totalMass", TYPE_REAL, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("particleMass", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("particleRadius", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("particleFriction", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("fixedParticles", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("constraintSetSetups", TYPE_ARRAY_OBJECT, "hclConstraintSetSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("perInstanceCollidables", TYPE_ARRAY_STRUCT, "hclSimClothSetupObjectPerInstanceCollidable", 0)
        HK_PATCH_DEPENDS("hclSimulationSetupMesh", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclConstraintSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclSimClothSetupObjectPerInstanceCollidable", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclStorageSetupMeshSectionSectionVertexFloatChannel", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclStorageSetupMeshSectionSectionVertexChannel")
        HK_PATCH_MEMBER_ADDED("vertexFloats", TYPE_ARRAY_REAL, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclStorageSetupMeshSectionSectionVertexChannel", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSceneDataSetupMeshSection", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
        HK_PATCH_MEMBER_ADDED("setupMesh", TYPE_OBJECT, "hclSceneDataSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("meshSection", TYPE_OBJECT, "hkxMeshSection", 0)
        HK_PATCH_MEMBER_ADDED("skinnedSection", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hkxMeshSection", 0)
        HK_PATCH_DEPENDS("hclSceneDataSetupMesh", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclStretchLinkSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclConstraintSetSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("simulationMesh", TYPE_OBJECT, "hclSimulationSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("movableParticlesSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("fixedParticlesSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("rigidFactor", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("stiffness", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("stretchDirection", TYPE_VEC_4, HK_NULL, 0)
        HK_PATCH_DEPENDS("hclSimulationSetupMesh", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclConstraintSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclOperatorSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclClothSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("bufferSetupObjects", TYPE_ARRAY_OBJECT, "hclBufferSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("transformSetSetupObjects", TYPE_ARRAY_OBJECT, "hclTransformSetSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("simClothSetupObjects", TYPE_ARRAY_OBJECT, "hclSimClothSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("operatorSetupObjects", TYPE_ARRAY_OBJECT, "hclOperatorSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("clothStateSetupObjects", TYPE_ARRAY_OBJECT, "hclClothStateSetupObject", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclClothStateSetupObject", 0)
        HK_PATCH_DEPENDS("hclTransformSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclOperatorSetupObject", 0)
        HK_PATCH_DEPENDS("hclSimClothSetupObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclRecalculateNormalsSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclOperatorSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("buffer", TYPE_OBJECT, "hclBufferSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("vertexSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclOperatorSetupObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBendLinkSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclConstraintSetSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("simulationMesh", TYPE_OBJECT, "hclSimulationSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("createStandardLinks", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("vertexSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("bendStiffness", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("stretchStiffness", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("flatnessFactor", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclSimulationSetupMesh", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclConstraintSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclStorageSetupMesh", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclSetupMesh")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("worldFromMesh", TYPE_VEC_16, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("sections", TYPE_ARRAY_OBJECT, "hclStorageSetupMeshSection", 0)
        HK_PATCH_MEMBER_ADDED("vertexChannels", TYPE_ARRAY_STRUCT, "hclStorageSetupMeshVertexChannel", 0)
        HK_PATCH_MEMBER_ADDED("triangleChannels", TYPE_ARRAY_STRUCT, "hclStorageSetupMeshTriangleChannel", 0)
        HK_PATCH_MEMBER_ADDED("bones", TYPE_ARRAY_STRUCT, "hclStorageSetupMeshBone", 0)
        HK_PATCH_MEMBER_ADDED("isSkinned", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("mode", TYPE_INT, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclStorageSetupMeshBone", 0)
        HK_PATCH_DEPENDS("hclStorageSetupMeshSection", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclStorageSetupMeshTriangleChannel", 0)
        HK_PATCH_DEPENDS("hclStorageSetupMeshVertexChannel", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBonePlanesSetupObjectPerParticlePlane", 0)
        HK_PATCH_MEMBER_ADDED("transformName", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("particles", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("directionBoneSpace", TYPE_VEC_4, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("allowedDistance", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("stiffness", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclVertexFloatInput", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclStaticDisplayBufferSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclBufferSetupObject")
        HK_PATCH_MEMBER_ADDED("setupMesh", TYPE_OBJECT, "hclSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclStorageSetupMeshSectionSectionVertexSelectionChannel", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclStorageSetupMeshSectionSectionVertexChannel")
        HK_PATCH_MEMBER_ADDED("vertexIndices", TYPE_ARRAY_INT, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclStorageSetupMeshSectionSectionVertexChannel", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclHingeSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclConstraintSetSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("simulationMesh", TYPE_OBJECT, "hclSimulationSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("vertexSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("hingeStiffness", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("relaxFactor", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclSimulationSetupMesh", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclConstraintSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclDisplayBufferSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclBufferSetupObject")
        HK_PATCH_MEMBER_ADDED("setupMesh", TYPE_OBJECT, "hclSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclStorageSetupMeshSectionSectionTriangleSelectionChannel", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
        HK_PATCH_MEMBER_ADDED("triangleIndices", TYPE_ARRAY_INT, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSkinSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclOperatorSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("transformSetSetup", TYPE_OBJECT, "hclTransformSetSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("referenceBufferSetup", TYPE_OBJECT, "hclBufferSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("outputBufferSetup", TYPE_OBJECT, "hclBufferSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("vertexSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("skinNormals", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("skinTangents", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("skinBiTangents", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclTransformSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclOperatorSetupObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclStorageSetupMeshSectionSectionVertexChannel", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclVertexGatherSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclOperatorSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("direction", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("simulationBuffer", TYPE_OBJECT, "hclSimClothBufferSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("simulationParticleSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("displayBuffer", TYPE_OBJECT, "hclBufferSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("displayVertexSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("gatherAllThreshold", TYPE_REAL, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("gatherNormals", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclOperatorSetupObject", 0)
        HK_PATCH_DEPENDS("hclSimClothBufferSetupObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclNamedSetupMesh", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclSetupMesh")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("meshName", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclStorageSetupMeshSection", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
        HK_PATCH_MEMBER_ADDED("parentSetupMesh", TYPE_OBJECT, "hclSetupMesh", 0)

        HK_PATCH_MEMBER_ADDED("vertices", TYPE_ARRAY_VEC_4, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("normals", TYPE_ARRAY_VEC_4, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("tangents", TYPE_ARRAY_VEC_4, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("bitangents", TYPE_ARRAY_VEC_4, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("triangles", TYPE_ARRAY_STRUCT, "hclSetupMeshSectionTriangle", 0)
        HK_PATCH_MEMBER_ADDED("sectionVertexChannels", TYPE_ARRAY_OBJECT, "hclStorageSetupMeshSectionSectionVertexChannel", 0)
        HK_PATCH_MEMBER_ADDED("sectionTriangleChannels", TYPE_ARRAY_OBJECT, "hclStorageSetupMeshSectionSectionTriangleSelectionChannel", 0)
        HK_PATCH_MEMBER_ADDED("boneInfluences", TYPE_ARRAY_OBJECT, "hclStorageSetupMeshSectionBoneInfluences", 0)
        HK_PATCH_DEPENDS("hclStorageSetupMeshSectionSectionTriangleSelectionChannel", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclSetupMeshSectionTriangle", 0)
        HK_PATCH_DEPENDS("hclStorageSetupMeshSectionBoneInfluences", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclStorageSetupMeshSectionSectionVertexChannel", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclMoveFixedParticlesSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclOperatorSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("simClothSetupObject", TYPE_OBJECT, "hclSimClothSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("displayBufferSetup", TYPE_OBJECT, "hclBufferSetupObject", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclOperatorSetupObject", 0)
        HK_PATCH_DEPENDS("hclSimClothSetupObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSimClothBufferSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclBufferSetupObject")
        HK_PATCH_MEMBER_ADDED("type", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("simClothSetupObject", TYPE_OBJECT, "hclSimClothSetupObject", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclSimClothSetupObject", 0)
        HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclClothSetupContainer", 0)
        HK_PATCH_MEMBER_ADDED("clothSetupDatas", TYPE_ARRAY_OBJECT, "hclClothSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("namedSetupMeshWrappers", TYPE_ARRAY_OBJECT, "hclNamedSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("namedTransformSetWrappers", TYPE_ARRAY_OBJECT, "hclNamedTransformSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclNamedSetupMesh", 0)
        HK_PATCH_DEPENDS("hclClothSetupObject", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclTransformSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclNamedTransformSetSetupObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBufferSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSceneDataSetupMesh", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclSetupMesh")
        HK_PATCH_MEMBER_ADDED("node", TYPE_OBJECT, "hkxNode", 0)
        HK_PATCH_MEMBER_ADDED("worldFromMesh", TYPE_VEC_16, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("mesh", TYPE_OBJECT, "hkxMesh", 0)
        HK_PATCH_MEMBER_ADDED("skinBinding", TYPE_OBJECT, "hkxSkinBinding", 0)
        HK_PATCH_MEMBER_ADDED("vertexChannels", TYPE_ARRAY_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("triangleChannels", TYPE_ARRAY_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("meshBufferInterfaces", TYPE_ARRAY_OBJECT, "hclSetupMeshSection", 0)
        HK_PATCH_DEPENDS("hkxMesh", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hkxAttributeHolder", 0)
        HK_PATCH_DEPENDS("hkxSkinBinding", 0)
        HK_PATCH_DEPENDS("hkxNode", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclSetupMeshSection", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclTransitionSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclConstraintSetSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("simulationMesh", TYPE_OBJECT, "hclSimulationSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("vertexSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("toAnimDelay", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("toSimDelay", TYPE_STRUCT, "hclVertexFloatInput",0)
        HK_PATCH_MEMBER_ADDED("toSimMaxDistance", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("toAnimPeriod", TYPE_REAL, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("toSimPeriod", TYPE_REAL, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("referenceBufferSetup", TYPE_OBJECT, "hclBufferSetupObject", 0)
        HK_PATCH_DEPENDS("hclSimulationSetupMesh", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclConstraintSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclStorageSetupMeshSectionBoneInfluences", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
        HK_PATCH_MEMBER_ADDED("boneIndices", TYPE_ARRAY_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("weights", TYPE_ARRAY_REAL, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclVolumeConstraintSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclConstraintSetSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("simulationMesh", TYPE_OBJECT, "hclSimulationSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("applyToParticles", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("stiffness", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("influenceParticles", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("particleWeights", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclSimulationSetupMesh", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclConstraintSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclLocalRangeSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclConstraintSetSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("simulationMesh", TYPE_OBJECT, "hclSimulationSetupMesh", 0)
        HK_PATCH_MEMBER_ADDED("vertexSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("maximumDistance", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("minNormalDistance", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("maxNormalDistance", TYPE_STRUCT, "hclVertexFloatInput", 0)
        HK_PATCH_MEMBER_ADDED("referenceBufferSetup", TYPE_OBJECT, "hclBufferSetupObject", 0)
        HK_PATCH_DEPENDS("hclSimulationSetupMesh", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclVertexFloatInput", 0)
        HK_PATCH_DEPENDS("hclConstraintSetSetupObject", 0)
        HK_PATCH_DEPENDS("hclSetupMesh", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclMeshMeshDeformSetupObject", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclOperatorSetupObject")
        HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("inputBufferSetupObject", TYPE_OBJECT, "hclBufferSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("inputTriangleSelection", TYPE_STRUCT, "hclTriangleSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("outputBufferSetupObject", TYPE_OBJECT, "hclBufferSetupObject", 0)
        HK_PATCH_MEMBER_ADDED("outputVertexSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
        HK_PATCH_MEMBER_ADDED("scaleNormalBehaviour", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("influenceRadius", TYPE_REAL, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("maxTrianglesPerVertex", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("minimumTriangleWeight", TYPE_REAL, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("inputTrianglesSubsetThreshold", TYPE_REAL, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("deformNormals", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
        HK_PATCH_DEPENDS("hclOperatorSetupObject", 0)
        HK_PATCH_DEPENDS("hclTriangleSelectionInput", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSetupMesh", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSetupMeshSection", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclClothStateSetupObject", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("operatorSetupObjects", TYPE_ARRAY_OBJECT, "hclOperatorSetupObject", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hclOperatorSetupObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclTransformSetSetupObject", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclStorageSetupMeshTriangleChannel", 0)
	HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("type", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclScratchBufferSetupObject", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hclBufferSetupObject")
	HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("setupMesh", TYPE_OBJECT, "hclSetupMesh", 0)
	HK_PATCH_MEMBER_ADDED("storeNormals", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("storeTangentsAndBiTangents", TYPE_BYTE, HK_NULL,0)
	HK_PATCH_MEMBER_ADDED("storeTriangles", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hclSetupMesh", 0)
	HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclStorageSetupMeshVertexChannel", 0)
	HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("type", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBlendSetupObject", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hclOperatorSetupObject")
	HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("A", TYPE_OBJECT, "hclBufferSetupObject", 0)
	HK_PATCH_MEMBER_ADDED("B", TYPE_OBJECT, "hclBufferSetupObject", 0)
	HK_PATCH_MEMBER_ADDED("C", TYPE_OBJECT, "hclBufferSetupObject", 0)
	HK_PATCH_MEMBER_ADDED("vertexSelection", TYPE_STRUCT, "hclVertexSelectionInput", 0)
	HK_PATCH_MEMBER_ADDED("blendWeights", TYPE_STRUCT, "hclVertexFloatInput", 0)
	HK_PATCH_MEMBER_ADDED("mapToScurve", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
	HK_PATCH_DEPENDS("hclVertexFloatInput", 0)
	HK_PATCH_DEPENDS("hclOperatorSetupObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
HK_PATCH_END()

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20130718)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
