/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

// Behavior specific product patches applied before release 660.
// This file is #included by hkbPatches_Legacy.cpp

HK_PATCH_BEGIN("hkbPredicate", 0, "hkbCondition", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbStringPredicate", 0, "hkbStringCondition", 0)
	HK_PATCH_MEMBER_RENAMED("predicateString", "conditionString")
HK_PATCH_END()

HK_PATCH_BEGIN("hkbClimbMountingPredicate", 0, "hkbClimbMountingCondition", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbExpressionData", 0)
	HK_PATCH_MEMBER_ADDED_CSTRING("expression", HK_NULL)
	HK_PATCH_MEMBER_ADDED("assignmentVariableIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("assignmentEventIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_INT("eventMode", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbRealEventPayload", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbEventPayload")
	HK_PATCH_MEMBER_ADDED("data", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventPayload", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbSceneModifierList", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbModifier")
	HK_PATCH_MEMBER_ADDED("sceneModifierEntries", TYPE_ARRAY_STRUCT, "hkbSceneModifierListSceneModifierEntry", 0)
	HK_PATCH_DEPENDS("hkbNode", 0)
	HK_PATCH_DEPENDS("hkbSceneModifierListSceneModifierEntry", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbClipTriggerArray", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("triggers", TYPE_ARRAY_STRUCT, "hkbClipTrigger", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbClipTrigger", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbNamedRealEventPayload", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbNamedEventPayload")
	HK_PATCH_MEMBER_ADDED("data", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventPayload", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbNamedEventPayload", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbRoleAttribute", 0)
	HK_PATCH_MEMBER_ADDED("role", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("flags", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbIntEventPayload", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbEventPayload")
	HK_PATCH_MEMBER_ADDED("data", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventPayload", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbComputeRotationToTargetModifier", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbModifier")
	HK_PATCH_MEMBER_ADDED_VEC_4("rotationOut", 0.000000f,0.000000f,0.000000f,1.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("targetPosition", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("currentPosition", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("currentRotation", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("localAxisOfRotation", 0.000000f,0.000000f,1.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("localFacingDirection", 1.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_BYTE("resultIsDelta", 0)
	HK_PATCH_DEPENDS("hkbNode", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbEventPayloadList", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbEventPayload")
	HK_PATCH_MEMBER_ADDED("payloads", TYPE_ARRAY_OBJECT, "hkbEventPayload", 0)
	HK_PATCH_DEPENDS("hkbEventPayload", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbComputeRotationFromAxisAngleModifier", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbModifier")
	HK_PATCH_MEMBER_ADDED_VEC_4("rotationOut", 0.000000f,0.000000f,0.000000f,1.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("axis", 1.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("angleDegrees", 0.000000f)
	HK_PATCH_DEPENDS("hkbNode", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbExpressionDataArray", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("expressionsData", TYPE_ARRAY_STRUCT, "hkbExpressionData", 0)
	HK_PATCH_DEPENDS("hkbExpressionData", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbCompiledExpressionSet", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("rpn", TYPE_ARRAY_STRUCT, "hkbCompiledExpressionSetToken", 0)
	HK_PATCH_MEMBER_ADDED("numExpressions", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbCompiledExpressionSetToken", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbCombineTransformsModifier", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbModifier")
	HK_PATCH_MEMBER_ADDED_VEC_4("translationOut", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("rotationOut", 0.000000f,0.000000f,0.000000f,1.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("leftTranslation", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("leftRotation", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("rightTranslation", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("rightRotation", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_BYTE("invertLeftTransform", 0)
	HK_PATCH_MEMBER_ADDED_BYTE("invertRightTransform", 0)
	HK_PATCH_MEMBER_ADDED_BYTE("invertResult", 0)
	HK_PATCH_DEPENDS("hkbNode", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbExpressionCondition", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbCondition")
	HK_PATCH_MEMBER_ADDED("expression", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("compiledExpressionSet", TYPE_OBJECT, "hkbCompiledExpressionSet", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbCompiledExpressionSet", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbCondition", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbBoneWeightArray", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbBindable")
	HK_PATCH_MEMBER_ADDED("boneWeights", TYPE_ARRAY_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbSenseHandleModifierRange", 0)
	HK_PATCH_MEMBER_ADDED("event", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_MEMBER_ADDED_REAL("minDistance", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("maxDistance", 1.000000f)
	HK_PATCH_MEMBER_ADDED("ignoreHandle", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbBindable", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("variableBindingSet", TYPE_OBJECT, "hkbVariableBindingSet", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbVariableBindingSet", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbSillyEventPayload", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbEventPayload")
	HK_PATCH_MEMBER_ADDED("sillyMessage", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("sillyGain", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("sillyIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("sillyEnum", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventPayload", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbBoneIndexArray", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbBindable")
	HK_PATCH_MEMBER_ADDED("boneIndices", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbNamedStringEventPayload", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbNamedEventPayload")
	HK_PATCH_MEMBER_ADDED("data", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventPayload", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbNamedEventPayload", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbNamedIntEventPayload", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbNamedEventPayload")
	HK_PATCH_MEMBER_ADDED("data", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventPayload", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbNamedEventPayload", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbEventProperty", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbEvent")
	HK_PATCH_DEPENDS("hkbEvent", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbEvaluateExpressionModifier", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbModifier")
	HK_PATCH_MEMBER_ADDED("expressions", TYPE_OBJECT, "hkbExpressionDataArray", 0)
	HK_PATCH_MEMBER_ADDED("compiledExpressionSet", TYPE_OBJECT, "hkbCompiledExpressionSet", 0)
	HK_PATCH_DEPENDS("hkbNode", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkbExpressionDataArray", 0)
	HK_PATCH_DEPENDS("hkbCompiledExpressionSet", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbNamedEventPayload", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbEventPayload")
	HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventPayload", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbVariableValueSet", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("wordVariableValues", TYPE_ARRAY_STRUCT, "hkbVariableValue", 0)
	HK_PATCH_MEMBER_ADDED("quadVariableValues", TYPE_ARRAY_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("variantVariableValues", TYPE_ARRAY_OBJECT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbVariableValue", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbStateMachineTransitionInfoArray", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("transitions", TYPE_ARRAY_STRUCT, "hkbStateMachineTransitionInfo", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbStateMachineTransitionInfo", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbStringEventPayload", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbEventPayload")
	HK_PATCH_MEMBER_ADDED("data", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventPayload", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbExtractRagdollPoseModifier", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbModifier")
	HK_PATCH_DEPENDS("hkbNode", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbStateListener", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbEventPayload", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbCompiledExpressionSetToken", 0)
	HK_PATCH_MEMBER_ADDED("data", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("type", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("operator", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbSceneModifierListSceneModifierEntry", 0)
	HK_PATCH_MEMBER_ADDED("sceneModifier", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("postSceneModifier", TYPE_OBJECT, "hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbNode", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbBallModifier", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbModifier")
	HK_PATCH_MEMBER_ADDED("velocity", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("applyForceEventId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("applyForce", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbNode", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbMoveBoneTowardTargetModifier", 0, "hkbMoveBoneTowardTargetModifier", 1)
	HK_PATCH_MEMBER_RENAMED("eventToSendWhenTargetReached", "old_eventToSendWhenTargetReached")
	HK_PATCH_MEMBER_ADDED("eventToSendWhenTargetReached", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_FUNCTION(hkbMoveBoneTowardTargetModifier_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_eventToSendWhenTargetReached", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacterStringData", 0, "hkbCharacterStringData", 1)
	HK_PATCH_MEMBER_ADDED("characterPropertyNames", TYPE_ARRAY_CSTRING, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbSplinePathGenerator", 0, "hkbSplinePathGenerator", 1)
	HK_PATCH_MEMBER_ADDED("pathEndEvent", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_FUNCTION(hkbSplinePathGenerator_0_to_1)
	HK_PATCH_MEMBER_REMOVED("pathEndEventId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbHandIkControlData", 0, "hkbHandIkControlData", 1)
	HK_PATCH_MEMBER_ADDED_VEC_4("targetRotation", 0.000000f,0.000000f,0.000000f,1.000000f)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbSenseHandleModifier", 0, "hkbSenseHandleModifier", 1)
	HK_PATCH_MEMBER_ADDED("ranges", TYPE_ARRAY_STRUCT, "hkbSenseHandleModifierRange", 0)
	HK_PATCH_MEMBER_ADDED_REAL("minDistance", 0.000000f)
	HK_PATCH_DEPENDS("hkbSenseHandleModifierRange", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbAttachmentModifier", 0, "hkbAttachmentModifier", 1)
	HK_PATCH_MEMBER_RENAMED("sendToAttacherOnAttach", "old_sendToAttacherOnAttach")
	HK_PATCH_MEMBER_ADDED("sendToAttacherOnAttach", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_MEMBER_RENAMED("sendToAttacheeOnAttach", "old_sendToAttacheeOnAttach")
	HK_PATCH_MEMBER_ADDED("sendToAttacheeOnAttach", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_MEMBER_RENAMED("sendToAttacherOnDetach", "old_sendToAttacherOnDetach")
	HK_PATCH_MEMBER_ADDED("sendToAttacherOnDetach", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_MEMBER_RENAMED("sendToAttacheeOnDetach", "old_sendToAttacheeOnDetach")
	HK_PATCH_MEMBER_ADDED("sendToAttacheeOnDetach", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_FUNCTION(hkbAttachmentModifier_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_sendToAttacherOnAttach", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("old_sendToAttacheeOnAttach", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("old_sendToAttacherOnDetach", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("old_sendToAttacheeOnDetach", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbTimerModifier", 0, "hkbTimerModifier", 1)
	HK_PATCH_MEMBER_ADDED("alarmEvent", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_FUNCTION(hkbTimerModifier_0_to_1)
	HK_PATCH_MEMBER_REMOVED("eventIdToSend", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbBehaviorGraphStringData", 0, "hkbBehaviorGraphStringData", 1)
	HK_PATCH_MEMBER_ADDED("characterPropertyNames", TYPE_ARRAY_CSTRING, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbTargetRigidBodyModifier", 0, "hkbTargetRigidBodyModifier", 1)
	HK_PATCH_MEMBER_RENAMED("eventToSend", "old_eventToSend")
	HK_PATCH_MEMBER_ADDED("eventToSend", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_MEMBER_RENAMED("eventToSendToTarget", "old_eventToSendToTarget")
	HK_PATCH_MEMBER_ADDED("eventToSendToTarget", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_MEMBER_ADDED("closeToTargetEvent", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_FUNCTION(hkbTargetRigidBodyModifier_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_eventToSend", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("old_eventToSendToTarget", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("closeToTargetEventId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbStateMachineProspectiveTransitionInfo", 0, "hkbStateMachineProspectiveTransitionInfo", 1)
	HK_PATCH_MEMBER_REMOVED("transitionInfo", TYPE_OBJECT, "hkbStateMachineTransitionInfo", 0)
	HK_PATCH_MEMBER_REMOVED("transitionEffect", TYPE_OBJECT, "hkbTransitionEffect", 0)
	HK_PATCH_MEMBER_REMOVED("toStateId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("isGlobalWildcard", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbNode", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbGenerator", 0)
	HK_PATCH_DEPENDS("hkbTransitionEffect", 0)
	HK_PATCH_DEPENDS("hkbStateMachineTransitionInfo", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbEvaluateHandleModifier", 0, "hkbEvaluateHandleModifier", 1)
	HK_PATCH_MEMBER_ADDED_REAL("extrapolationTimeStep", 0.000000f)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbDetectCloseToGroundModifier", 0, "hkbDetectCloseToGroundModifier", 1)
	HK_PATCH_MEMBER_ADDED("closeToGroundEvent", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_FUNCTION(hkbDetectCloseToGroundModifier_0_to_1)
	HK_PATCH_MEMBER_REMOVED("closeToGroundEventId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbAttachmentSetup", 0, "hkbAttachmentSetup", 1)
	HK_PATCH_MEMBER_ADDED_REAL("extrapolationTimeStep", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("fixUpGain", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("maxLinearDistance", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("maxAngularDistance", 0.000000f)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbFootIkModifierInternalLegData", 0, "hkbFootIkModifierInternalLegData", 1)
	HK_PATCH_MEMBER_REMOVED("verticalError", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("hitSomething", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("isPlanted", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbLookAtModifier", 0, "hkbLookAtModifier", 1)
	HK_PATCH_MEMBER_REMOVED("lookUp", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("lookUpAngleDegrees", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("individualLimitsOn", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_REAL("limitAngleLeft", 90.0f)
	HK_PATCH_MEMBER_ADDED_REAL("limitAngleRight", -90.0f)
	HK_PATCH_MEMBER_ADDED_REAL("limitAngleUp", 30.0f)
	HK_PATCH_MEMBER_ADDED_REAL("limitAngleDown", -30.0f)
	//HK_PATCH_FUNCTION(hkbLookAtModifier_0_to_1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbVariableBindingSetBinding", 0, "hkbVariableBindingSetBinding", 1)
	HK_PATCH_MEMBER_ADDED("bindingType", TYPE_INT, HK_NULL, 0)
	HK_PATCH_FUNCTION(hkbVariableBindingSetBinding_0_to_1)
	HK_PATCH_MEMBER_REMOVED("object", TYPE_OBJECT, "hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbVariableBindingSet", 0)
	// The following should include all class that existed in version 0 and were made subclasses of hkbBindable in version 1.
	// It also includes any objects that were converted to using hkbBoneIndexArray or hkbBoneWeightArray.
	HK_PATCH_DEPENDS("hkbNode", 1)
	HK_PATCH_DEPENDS("hkbJigglerGroup", 1)
	HK_PATCH_DEPENDS("hkbBlenderGeneratorChild", 1)
	HK_PATCH_DEPENDS("hkbRegisteredGenerator", 1)
	HK_PATCH_DEPENDS("hkbPoweredRagdollControlsModifier", 1)
	HK_PATCH_DEPENDS("hkbKeyframeBonesModifier", 1)
	HK_PATCH_DEPENDS("hkbRigidBodyRagdollModifier", 1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbVariableBindingSet", 0, "hkbVariableBindingSet", 1 )
	HK_PATCH_FUNCTION(hkbVariableBindingSet_0_to_1)
	HK_PATCH_DEPENDS("hkbVariableBindingSetBinding", 1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbNode", 0, "hkbNode", 1)
	HK_PATCH_MEMBER_RENAMED( "variableBindingSet", "old_variableBindingSet" )
	HK_PATCH_PARENT_SET("hkReferencedObject", "hkbBindable")
	HK_PATCH_FUNCTION(hkbNode_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_variableBindingSet", TYPE_OBJECT, "hkbVariableBindingSet", 0)
	HK_PATCH_DEPENDS("hkbVariableBindingSet", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbHandIkModifierHand", 0, "hkbHandIkModifierHand", 1)
	HK_PATCH_MEMBER_ADDED_VEC_4("handOffsetLS", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4_IDENTITY("handOrienationOffsetLS")
	HK_PATCH_MEMBER_ADDED_BOOL("enforceEndPosition", true)
	HK_PATCH_MEMBER_ADDED_BYTE("enforceEndRotation", 0)
	HK_PATCH_MEMBER_ADDED_CSTRING("localFrameName", HK_NULL)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbVariableInfo", 0, "hkbVariableInfo", 1)
	HK_PATCH_MEMBER_REMOVED("initialValue", TYPE_STRUCT, "hkbVariableValue", 0)
	HK_PATCH_MEMBER_ADDED("role", TYPE_STRUCT, "hkbRoleAttribute", 0)
	HK_PATCH_DEPENDS("hkbVariableValue", 0)
	HK_PATCH_DEPENDS("hkbRoleAttribute", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbPositionRelativeSelectorGenerator", 0, "hkbPositionRelativeSelectorGenerator", 1)
	HK_PATCH_MEMBER_ADDED("fixPositionEvent", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_FUNCTION(hkbPositionRelativeSelectorGenerator_0_to_1)
	HK_PATCH_MEMBER_REMOVED("fixPositionEventId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCheckRagdollSpeedModifier", 0, "hkbCheckRagdollSpeedModifier", 1)
	HK_PATCH_MEMBER_RENAMED("eventToSend", "old_eventToSend")
	HK_PATCH_MEMBER_ADDED("eventToSend", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_FUNCTION(hkbCheckRagdollSpeedModifier_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_eventToSend", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacterData", 0, "hkbCharacterData", 1)
	HK_PATCH_MEMBER_ADDED("characterPropertyInfos", TYPE_ARRAY_STRUCT, "hkbVariableInfo", 0)
	HK_PATCH_MEMBER_ADDED("characterPropertyValues", TYPE_OBJECT, "hkbVariableValueSet", 0)
	HK_PATCH_DEPENDS("hkbVariableInfo", 1)
	HK_PATCH_DEPENDS("hkbVariableValueSet", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbFootIkModifierLeg", 0, "hkbFootIkModifierLeg", 1)
	HK_PATCH_MEMBER_ADDED("ungroundedEvent", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_FUNCTION(hkbFootIkModifierLeg_0_to_1)
	HK_PATCH_MEMBER_ADDED_REAL("verticalError", 0.000000f)
	HK_PATCH_MEMBER_ADDED_BYTE("hitSomething", 0)
	HK_PATCH_MEMBER_ADDED_BYTE("isPlantedMS", 0)
	HK_PATCH_MEMBER_REMOVED("ungroundedEventId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbClipTrigger", 0, "hkbClipTrigger", 1)
	HK_PATCH_MEMBER_RENAMED("event", "old_event")
	HK_PATCH_MEMBER_ADDED("event", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_FUNCTION(hkbClipTrigger_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_event", TYPE_STRUCT, "hkbEvent", 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbClipGenerator", 0, "hkbClipGenerator", 1)
	HK_PATCH_MEMBER_RENAMED("triggers", "old_triggers")
	HK_PATCH_MEMBER_ADDED("triggers", TYPE_OBJECT, "hkbClipTriggerArray", 0)
	HK_PATCH_MEMBER_ADDED_INT("animationBindingIndex", -1)
	HK_PATCH_FUNCTION(hkbClipGenerator_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_triggers", TYPE_ARRAY_STRUCT, "hkbClipTrigger", 0)
	HK_PATCH_DEPENDS("hkbClipTrigger", 0)
	HK_PATCH_DEPENDS("hkbClipTriggerArray", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbFootIkModifier", 0, "hkbFootIkModifier", 1)
	HK_PATCH_MEMBER_ADDED_REAL("verticalOffset", 0.000000f)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCatchFallModifier", 0, "hkbCatchFallModifier", 1)
	HK_PATCH_MEMBER_RENAMED("spineIndices", "old_spineIndices")
	HK_PATCH_MEMBER_ADDED("spineIndices", TYPE_OBJECT, "hkbBoneIndexArray", 0)
	HK_PATCH_MEMBER_ADDED("catchFallDoneEvent", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_FUNCTION(hkbCatchFallModifier_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_spineIndices", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("catchFallDoneEventId", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
	HK_PATCH_DEPENDS("hkbBoneIndexArray", 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbStateMachineStateInfo", 0, "hkbStateMachineStateInfo", 1)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_RENAMED("enterNotifyEvent", "old_enterNotifyEvent")
	HK_PATCH_MEMBER_ADDED("enterNotifyEvent", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_MEMBER_RENAMED("exitNotifyEvent", "old_exitNotifyEvent")
	HK_PATCH_MEMBER_ADDED("exitNotifyEvent", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_MEMBER_ADDED("listeners", TYPE_ARRAY_OBJECT, "hkbStateListener", 0)
	HK_PATCH_FUNCTION(hkbStateMachineStateInfo_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_enterNotifyEvent", TYPE_STRUCT, "hkbEvent", 0)
	HK_PATCH_MEMBER_REMOVED("old_exitNotifyEvent", TYPE_STRUCT, "hkbEvent", 0)
	HK_PATCH_MEMBER_REMOVED("inPackfile", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
	HK_PATCH_DEPENDS("hkbStateListener", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbBehaviorGraphData", 0, "hkbBehaviorGraphData", 1)
	HK_PATCH_MEMBER_ADDED("characterPropertyInfos", TYPE_ARRAY_STRUCT, "hkbVariableInfo", 0)
	HK_PATCH_MEMBER_ADDED("variableInitialValues", TYPE_OBJECT, "hkbVariableValueSet", 0)
	HK_PATCH_FUNCTION(hkbBehaviorGraphData_0_to_1)
	HK_PATCH_MEMBER_REMOVED("quadVariableInitialValues", TYPE_ARRAY_VEC_4, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbVariableInfo", 0)
	HK_PATCH_DEPENDS("hkbVariableValueSet", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbStateMachineTransitionInfo", 0, "hkbStateMachineTransitionInfo", 1)
	HK_PATCH_MEMBER_RENAMED("predicate", "condition")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbCondition", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbPoweredRagdollControlsModifier", 0, "hkbPoweredRagdollControlsModifier", 1)
	HK_PATCH_MEMBER_RENAMED("boneWeights", "old_boneWeights")
	HK_PATCH_MEMBER_ADDED("boneWeights", TYPE_OBJECT, "hkbBoneWeightArray", 0)
	HK_PATCH_FUNCTION(hkbPoweredRagdollControlsModifier_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_boneWeights", TYPE_ARRAY_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbBoneWeightArray", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbStateMachine", 0, "hkbStateMachine", 1)
	HK_PATCH_MEMBER_ADDED("wildcardTransitions", TYPE_OBJECT, "hkbStateMachineTransitionInfoArray", 0)
	HK_PATCH_FUNCTION(hkbStateMachine_0_to_1)
	HK_PATCH_MEMBER_REMOVED("globalTransitions", TYPE_ARRAY_STRUCT, "hkbStateMachineTransitionInfo", 0)
	HK_PATCH_DEPENDS("hkbStateMachineTransitionInfo", 0)
	HK_PATCH_DEPENDS("hkbStateMachineTransitionInfoArray", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbKeyframeBonesModifier", 0, "hkbKeyframeBonesModifier", 1)
	HK_PATCH_MEMBER_RENAMED("keyframedBonesList", "old_keyframedBonesList")
	HK_PATCH_MEMBER_ADDED("keyframedBonesList", TYPE_OBJECT, "hkbBoneIndexArray", 0)
	HK_PATCH_FUNCTION(hkbKeyframeBonesModifier_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_keyframedBonesList", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbBoneIndexArray", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbBlenderGeneratorChild", 0, "hkbBlenderGeneratorChild", 1)
	HK_PATCH_PARENT_SET("hkReferencedObject", "hkbBindable")
	HK_PATCH_MEMBER_RENAMED("boneWeights", "old_boneWeights")
	HK_PATCH_MEMBER_ADDED("boneWeights", TYPE_OBJECT, "hkbBoneWeightArray", 0)
	HK_PATCH_FUNCTION(hkbBlenderGeneratorChild_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_boneWeights", TYPE_ARRAY_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbBoneWeightArray", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRigidBodyRagdollModifier", 0, "hkbRigidBodyRagdollModifier", 1)
	HK_PATCH_MEMBER_RENAMED("keyframedBonesList", "old_keyframedBonesList")
	HK_PATCH_MEMBER_ADDED("keyframedBonesList", TYPE_OBJECT, "hkbBoneIndexArray", 0)
	HK_PATCH_FUNCTION(hkbRigidBodyRagdollModifier_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_keyframedBonesList", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbBoneIndexArray", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbJigglerGroup", 0, "hkbJigglerGroup", 1)
	HK_PATCH_PARENT_SET("hkReferencedObject", "hkbBindable")
	HK_PATCH_MEMBER_RENAMED("boneIndices", "old_boneIndices")
	HK_PATCH_MEMBER_ADDED("boneIndices", TYPE_OBJECT, "hkbBoneIndexArray", 0)
	HK_PATCH_FUNCTION(hkbJigglerGroup_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_boneIndices", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbBoneIndexArray", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRegisteredGenerator", 0, "hkbRegisteredGenerator", 1)
	HK_PATCH_PARENT_SET("hkReferencedObject", "hkbBindable")
	HK_PATCH_DEPENDS("hkbBindable", 0)
HK_PATCH_END()

//=======
// 650r1
//=======

HK_PATCH_BEGIN("hkbSillyEventPayload", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkbEventPayload", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("sillyMessage", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("sillyGain", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("sillyIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("sillyEnum", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbEventPayload", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbStateMachineStateInfo", 1, "hkbStateMachineStateInfo", 2)
	HK_PATCH_PARENT_SET("hkReferencedObject", "hkbBindable")
	HK_PATCH_MEMBER_RENAMED("transitions","old_transitions")
	HK_PATCH_MEMBER_ADDED("transitions", TYPE_OBJECT, "hkbStateMachineTransitionInfoArray", 0)
	HK_PATCH_MEMBER_ADDED_BYTE("enable", 1)
	HK_PATCH_DEPENDS("hkbStateMachineTransitionInfo", 1)
	HK_PATCH_DEPENDS("hkbStateMachineTransitionInfoArray", 0)
	HK_PATCH_FUNCTION(hkbStateMachineStateInfo_1_to_2)
	HK_PATCH_MEMBER_REMOVED("old_transitions", TYPE_ARRAY_STRUCT, "hkbStateMachineTransitionInfo", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRotateCharacterModifier", 0, "hkbRotateCharacterModifier", 1)
	HK_PATCH_MEMBER_ADDED_REAL("speedMultiplier", 1.000000f)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCompiledExpressionSet", 0, "hkbCompiledExpressionSet", 1)
	HK_PATCH_MEMBER_ADDED("expressionToRpnIndex", TYPE_ARRAY_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacterData", 1, "hkbCharacterData", 2)
        HK_PATCH_MEMBER_ADDED_REAL("scale", 1.000000f)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbDemoConfigStickVariableInfo", 0, "hkbDemoConfigStickVariableInfo", 1)
	HK_PATCH_MEMBER_ADDED_REAL("minStickValue", -1.0f)
	HK_PATCH_MEMBER_ADDED_REAL("maxStickValue", 1.0f)
	HK_PATCH_MEMBER_ADDED("stickAxis", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("stick", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("complimentVariableValue", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("negateVariableValue", TYPE_BYTE, HK_NULL, 0)
	//HK_PATCH_FUNCTION(hkbDemoConfigStickVariableInfo_0_to_1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbDemoConfig", 0, "hkbDemoConfig", 1)
	HK_PATCH_MEMBER_RENAMED("stickVariables", "old_stickVariables")
	HK_PATCH_MEMBER_ADDED("stickVariables", TYPE_TUPLE_STRUCT, "hkbDemoConfigStickVariableInfo", 12)
	HK_PATCH_FUNCTION(hkbDemoConfig_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_stickVariables", TYPE_TUPLE_STRUCT, "hkbDemoConfigStickVariableInfo", 4)
	HK_PATCH_DEPENDS("hkbDemoConfigStickVariableInfo", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbProxyModifier", 0, "hkbProxyModifier", 1)
	HK_PATCH_MEMBER_ADDED_BOOL("includeDownwardMomentum", true)
	HK_PATCH_MEMBER_ADDED_BOOL("followWorldFromModel", true)
	HK_PATCH_MEMBER_ADDED_BYTE("isTouchingGround", 1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbDampingModifier", 0, "hkbDampingModifier", 1)
	HK_PATCH_MEMBER_ADDED_BOOL("enableScalarDamping", true)
	HK_PATCH_MEMBER_ADDED_BYTE("enableVectorDamping", 0)
	HK_PATCH_MEMBER_ADDED_VEC_4("rawVector", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("dampedVector", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("vecErrorSum", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("vecPreviousError", 0.000000f,0.000000f,0.000000f,0.000000f)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbVariableBindingSet", 1, "hkbVariableBindingSet", 2)
	HK_PATCH_MEMBER_ADDED_INT("indexOfBindingToEnable", -1)
	HK_PATCH_FUNCTION(hkbVariableBindingSet_1_to_2)
HK_PATCH_END()

//==========
// post-6.5
//==========

// Note that these targetting modifiers are being versioned but the behavior graphs
// That used them will not work.  In particular, there may be variables bound to the members
// that were removed.  If we really want to version such behavior graphs we'll have
// to change some of the variable types from int to hkbTarget* and change the
// bindings to point to the new members.

HK_PATCH_BEGIN("hkbMoveBoneTowardTargetModifier", 1, "hkbMoveBoneTowardTargetModifier", 2)
	HK_PATCH_MEMBER_REMOVED("target", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("clearTargetData", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("currentBoneIsValidIn", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("behaviorTarget", TYPE_OBJECT, "hkbTarget", 0)
	HK_PATCH_MEMBER_ADDED_POINTER("targetIn", "hkbTarget", 0)
	HK_PATCH_DEPENDS("hkbTarget", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbFaceTargetModifier", 0, "hkbFaceTargetModifier", 1)
	HK_PATCH_MEMBER_REMOVED("target", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("behaviorTarget", TYPE_OBJECT, "hkbTarget", 0)
	HK_PATCH_MEMBER_ADDED_POINTER("targetIn", "hkbTarget", 0)
	HK_PATCH_DEPENDS("hkbTarget", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbPoweredRagdollModifierKeyframeInfo", 0, "hkbPoweredRagdollModifierKeyframeInfo", 1)
	HK_PATCH_MEMBER_REMOVED("isValidOut", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbReachTowardTargetModifier", 0, "hkbReachTowardTargetModifier", 1)
	HK_PATCH_MEMBER_REMOVED("target", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("clearTargetData", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("behaviorTarget", TYPE_OBJECT, "hkbTarget", 0)
	HK_PATCH_MEMBER_ADDED_POINTER("targetIn", "hkbTarget", 0)
	HK_PATCH_DEPENDS("hkbTarget", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbTargetRigidBodyModifier", 1, "hkbTargetRigidBodyModifier", 2)
	HK_PATCH_MEMBER_REMOVED("target", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("targetIn", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_POINTER("targetOut", "hkbTarget", 0)
	HK_PATCH_MEMBER_ADDED_BYTE("isCloseToTargetOut", 0)
	HK_PATCH_DEPENDS("hkbTarget", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbConstrainRigidBodyModifier", 0, "hkbConstrainRigidBodyModifier", 1)
	HK_PATCH_MEMBER_REMOVED("target", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("behaviorTarget", TYPE_OBJECT, "hkbTarget", 0)
	HK_PATCH_MEMBER_ADDED_POINTER("targetIn", "hkbTarget", 0)
	HK_PATCH_DEPENDS("hkbTarget", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbTargetRigidBodyModifier", 2, "hkbTargetRigidBodyModifier", 3)
	HK_PATCH_MEMBER_REMOVED("behaviorTarget", TYPE_OBJECT, "hkbTarget", 0)
	HK_PATCH_MEMBER_REMOVED("closeToTargetEventHasBeenSent", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbTarget", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbTarget", 0, "hkbTarget", 1)
	HK_PATCH_PARENT_SET("hkReferencedObject", HK_NULL)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbClimbMountingCondition", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkbCondition", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("maxTargetDistance", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("sensingForLeftHand", TYPE_OBJECT, "hkbTargetRigidBodyModifier", 0)
	HK_PATCH_MEMBER_REMOVED("sensingForRightHand", TYPE_OBJECT, "hkbTargetRigidBodyModifier", 0)
	HK_PATCH_MEMBER_REMOVED("targetForLeftHand", TYPE_OBJECT, "hkbTarget", 0)
	HK_PATCH_MEMBER_REMOVED("targetForRightHand", TYPE_OBJECT, "hkbTarget",	0)
	HK_PATCH_DEPENDS("hkbTarget", 0)
	HK_PATCH_DEPENDS("hkbNode", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbTargetRigidBodyModifier", 3)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbCondition", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbBlenderGeneratorChild", 1, "hkbBlenderGeneratorChild", 2)
	HK_PATCH_MEMBER_REMOVED("operandType", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbBlenderGenerator", 0, "hkbBlenderGenerator", 1)
	HK_PATCH_MEMBER_ADDED_BYTE("subtractLastChild", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbGeneratorOutputTrackHeader", 0, "hkbGeneratorOutputTrackHeader", 1)
	HK_PATCH_MEMBER_REMOVED("format", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isPoseAdditive", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbStateMachineStateInfo", 2, "hkbStateMachineStateInfo", 3)
	HK_PATCH_MEMBER_ADDED_REAL("probability", 1.0f)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacterStringData", 1, "hkbCharacterStringData", 2)
	HK_PATCH_MEMBER_ADDED("behaviorFilename", TYPE_CSTRING, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbDemoConfigCharacterInfo", 0, "hkbDemoConfigCharacterInfo", 1)
	HK_PATCH_MEMBER_REMOVED("rigFilename", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("skinFilenames", TYPE_ARRAY_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("behaviorFilename", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("attachmentsFilename", TYPE_CSTRING, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRagdollDriverModifier", 0, "hkbRagdollDriverModifier", 1)
	HK_PATCH_MEMBER_ADDED_REAL("blendRagdollPoseFraction", 1.0f)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbSimpleCharacter", 0, "hkbSimpleCharacter", 1)
	HK_PATCH_MEMBER_ADDED("ragdollWorldFromModel", TYPE_VEC_12, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbDefaultMessageLog", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbMessageLog", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbEvaluateHandleModifier", 1, "hkbEvaluateHandleModifier", 2)
	HK_PATCH_MEMBER_ADDED_REAL("handleChangeSpeed", 1.0f)
	HK_PATCH_MEMBER_ADDED_INT("handleChangeMode", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRagdollDriverModifier", 1, "hkbRagdollDriverModifier", 2)
	HK_PATCH_MEMBER_REMOVED("isRagdollForceModifierActive", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_REAL("ragdollBlendOutTime", 0.25f)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbEventsFromRangeModifier", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbModifier")
	HK_PATCH_MEMBER_ADDED("inputValue", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("lowerBound", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("eventRanges", TYPE_OBJECT, "hkbEventRangeDataArray", 0)
	HK_PATCH_DEPENDS("hkbNode", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbEventRangeDataArray", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbEventRangeData", 0)
	HK_PATCH_MEMBER_ADDED("upperBound", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("event", TYPE_STRUCT, "hkbEventProperty", 0)
	HK_PATCH_MEMBER_ADDED_INT("eventMode", 0)
	HK_PATCH_DEPENDS("hkbEventProperty", 0)
	HK_PATCH_DEPENDS("hkbEvent", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbEventRangeDataArray", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("eventData", TYPE_ARRAY_STRUCT, "hkbEventRangeData", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbEventRangeData", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbRagdollController", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED("ragdollBlendOutTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("poseMatchingBone0", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("poseMatchingBone1", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("poseMatchingBone2", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("worldFromModelMode", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("character", TYPE_OBJECT, "hkbCharacter", 0)
	HK_PATCH_MEMBER_ADDED("ragdollInstance", TYPE_OBJECT, "hkaRagdollInstance", 0)
	HK_PATCH_MEMBER_ADDED("ragdollPoseWS", TYPE_OBJECT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("rigidBodyControllerBlendTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("firstGenerateAfterRagdollIsAddedToWorld", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("firstGenerateAfterRigidBodyControllerActive", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("autoAddRemoveRagdollToWorld", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isEnabled", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isPoweredControllerEnabled", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("isRigidBodyControllerEnabled", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbCharacter", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkaRagdollInstance", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbRagdollModifier", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkbModifier")
	HK_PATCH_MEMBER_ADDED("poweredControlData", TYPE_STRUCT, "hkbPoweredRagdollControlData", 0)
	HK_PATCH_MEMBER_ADDED("rigidBodyControlData", TYPE_STRUCT, "hkaKeyFrameHierarchyUtilityControlData", 0)
	HK_PATCH_MEMBER_ADDED("poweredBoneWeights", TYPE_OBJECT, "hkbBoneWeightArray", 0)
	HK_PATCH_MEMBER_ADDED("rigidBodyBoneWeights", TYPE_OBJECT, "hkbBoneWeightArray", 0)
	HK_PATCH_MEMBER_ADDED("rigidBodyControllerBlendTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("enablePoweredController", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("enableRigidBodyController", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("setTargetPose", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("justSetTargetPose", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbNode", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkaKeyFrameHierarchyUtilityControlData", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkbPoweredRagdollControlData", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbBoneWeightArray", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbExtractRagdollPoseModifier", 0, "hkbExtractRagdollPoseModifier", 1)
	HK_PATCH_MEMBER_ADDED_INT("poseMatchingBone0", -1)
	HK_PATCH_MEMBER_ADDED_INT("poseMatchingBone1", -1)
	HK_PATCH_MEMBER_ADDED_INT("poseMatchingBone2", -1)
	HK_PATCH_MEMBER_ADDED_BOOL("enableComputeWorldFromModel", false)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbSimpleCharacter", 1, "hkbSimpleCharacter", 2)
	HK_PATCH_MEMBER_REMOVED("ragdollInstance", TYPE_OBJECT, "hkaRagdollInstance", 0)
	HK_PATCH_MEMBER_ADDED("ragdollController", TYPE_OBJECT, "hkbRagdollController", 0)
	HK_PATCH_DEPENDS("hkaRagdollInstance", 0)
	HK_PATCH_DEPENDS("hkbRagdollController", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbBalanceControllerModifier", 0, "hkbBalanceControllerModifier" , 1)
	HK_PATCH_MEMBER_ADDED_INT("pelvisIndex", -1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacterData", 2, "hkbCharacterData", 3)
	HK_PATCH_MEMBER_REMOVED("animationBoneInfo", TYPE_STRUCT, "hkbCharacterBoneInfo", 0)
	HK_PATCH_MEMBER_REMOVED("ragdollBoneInfo", TYPE_STRUCT, "hkbCharacterBoneInfo", 0)
	HK_PATCH_DEPENDS("hkbCharacterBoneInfo", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbReachTowardTargetModifierHand", 0, "hkbReachTowardTargetModifierHand", 1)
	HK_PATCH_MEMBER_REMOVED("handIndex", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCatchFallModifierHand", 0, "hkbCatchFallModifierHand", 1)
	HK_PATCH_MEMBER_REMOVED("handIndex", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbFootIkModifierLeg", 1, "hkbFootIkModifierLeg", 2)
	HK_PATCH_MEMBER_REMOVED("legIndex", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbHandIkModifierHand", 1, "hkbHandIkModifierHand", 2)
	HK_PATCH_MEMBER_REMOVED("handIndex", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacterBoneInfo", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_MEMBER_REMOVED("clavicleIndex", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("shoulderIndex", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("elbowIndex", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("wristIndex", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("hipIndex", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("kneeIndex", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("ankleIndex", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("spineIndex", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("pelvisIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("neckIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("headIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("poseMatchingRootBoneIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("poseMatchingOtherBoneIndex", TYPE_INT, HK_NULL,  0)
	HK_PATCH_MEMBER_REMOVED("poseMatchingAnotherBoneIndex", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbBehaviorGraphData", 1, "hkbBehaviorGraphData", 2)
	HK_PATCH_MEMBER_ADDED("wordMinVariableValues", TYPE_ARRAY_STRUCT, "hkbVariableValue", 0)
	HK_PATCH_MEMBER_ADDED("wordMaxVariableValues", TYPE_ARRAY_STRUCT, "hkbVariableValue", 0)
	HK_PATCH_DEPENDS("hkbVariableValue", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbDetectCloseToGroundModifier", 1, "hkbDetectCloseToGroundModifier", 2)
	HK_PATCH_MEMBER_ADDED_INT("animBoneIndex", -1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbKeyframeBonesModifier", 1, "hkbKeyframeBonesModifier", 2)
	HK_PATCH_MEMBER_REMOVED("keyframedBones", TYPE_STRUCT, "hkBitField", 0)
	HK_PATCH_DEPENDS("hkBitField", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbSenseHandleModifier", 1, "hkbSenseHandleModifier", 2)
        HK_PATCH_MEMBER_ADDED_INT("collisionFilterInfo", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbGeneratorTransitionEffect", 0, "hkbGeneratorTransitionEffect", 1)
        HK_PATCH_MEMBER_ADDED_BOOL("syncToGeneratorStartTime", true)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbKeyframeBonesModifierKeyframeInfo", 0)
	HK_PATCH_MEMBER_ADDED_VEC_4("keyframedPosition", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("keyframedRotation", 0.000000f,0.000000f,0.000000f,1.000000f)
	HK_PATCH_MEMBER_ADDED_INT("boneIndex", -1)
	HK_PATCH_MEMBER_ADDED_BYTE("isValid", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRagdollDriverModifier", 2, "hkbRagdollDriverModifier", 3)
	HK_PATCH_MEMBER_REMOVED("addRagdollToWorld", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("removeRagdollFromWorld", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("poweredRagdollModifier", TYPE_OBJECT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("rigidBodyRagdollModifier", TYPE_OBJECT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("ragdollForceModifier", TYPE_OBJECT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("blendRagdollPoseFraction", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("ragdollBlendOutTime", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbPoweredRagdollModifierKeyframeInfo", 1, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_MEMBER_REMOVED("keyframedPosition", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("keyframedRotation", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("boneIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("isValid", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRagdollForceModifier", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkbModifier", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("boneForces", TYPE_ARRAY_VEC_4, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbNode", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRigidBodyRagdollModifier", 1, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkbModifier", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("controlDataPalette", TYPE_ARRAY_STRUCT, "hkaKeyFrameHierarchyUtilityControlData", 0)
	HK_PATCH_MEMBER_REMOVED("bodyIndexToPaletteIndex", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("keyframedBones", TYPE_STRUCT, "hkBitField", 0)
	HK_PATCH_MEMBER_REMOVED("keyframedBonesList", TYPE_OBJECT, "hkbBoneIndexArray", 0)
	HK_PATCH_DEPENDS("hkBitField", 0)
	HK_PATCH_DEPENDS("hkbNode", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkaKeyFrameHierarchyUtilityControlData", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkbBoneIndexArray", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbPoweredRagdollModifier", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkbModifier", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("floorRaycastLayer", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("controls", TYPE_STRUCT, "hkbPoweredRagdollControlData", 0)
	HK_PATCH_MEMBER_REMOVED("blendInTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("computeWorldFromModelMode", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("fixConstraintsTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("useLocking", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("keyframeInfo", TYPE_ARRAY_STRUCT, "hkbPoweredRagdollModifierKeyframeInfo", 0)
	HK_PATCH_MEMBER_REMOVED("rootBoneIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("otherBoneIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("anotherBoneIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("keyframedBones", TYPE_STRUCT, "hkBitField", 0)
	HK_PATCH_MEMBER_REMOVED("boneWeights", TYPE_ARRAY_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBitField", 0)
	HK_PATCH_DEPENDS("hkbNode", 1)
	HK_PATCH_DEPENDS("hkbPoweredRagdollModifierKeyframeInfo", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkbPoweredRagdollControlData", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbKeyframeBonesModifier", 2, "hkbKeyframeBonesModifier", 3)
	HK_PATCH_MEMBER_ADDED("keyframeInfo", TYPE_ARRAY_STRUCT, "hkbKeyframeBonesModifierKeyframeInfo", 0)
	HK_PATCH_DEPENDS("hkbKeyframeBonesModifierKeyframeInfo", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRigidBodyRagdollControlsModifier", 0, "hkbRigidBodyRagdollControlsModifier", 1)
	HK_PATCH_MEMBER_ADDED("bones", TYPE_OBJECT, "hkbBoneIndexArray", 0)
	HK_PATCH_DEPENDS("hkbBoneIndexArray", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbPoweredRagdollControlsModifier", 1, "hkbPoweredRagdollControlsModifier", 2)
	HK_PATCH_MEMBER_ADDED("setTargetPose", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRigidBodyRagdollControlsModifier", 1, "hkbRigidBodyRagdollControlsModifier", 2)
	HK_PATCH_MEMBER_ADDED("setTargetPose", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRagdollModifier", 0, "hkbRagdollModifier", 1)
	HK_PATCH_MEMBER_ADDED("poseMatchingBone0", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("poseMatchingBone1", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("poseMatchingBone2", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("worldFromModelMode", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbPoweredRagdollControlsModifier", 2, "hkbPoweredRagdollControlsModifier", 3)
	HK_PATCH_MEMBER_ADDED("poseMatchingBone0", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("poseMatchingBone1", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("poseMatchingBone2", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("worldFromModelMode", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbClipGenerator", 1, "hkbClipGenerator", 2)
	HK_PATCH_FUNCTION(hkbClipGenerator_1_to_2)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbFootIkModifier", 1, "hkbFootIkModifier", 2)
	HK_PATCH_MEMBER_ADDED_INT("alignMode", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbGeneratorOutputTrackMasterHeader", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_MEMBER_REMOVED("numBytes", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("numTracks", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("unused", TYPE_TUPLE_INT, HK_NULL, 2)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbGeneratorOutputConstTrack", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_MEMBER_REMOVED("header", TYPE_OBJECT, "hkbGeneratorOutputTrackHeader", 0)
	HK_PATCH_MEMBER_REMOVED("data", TYPE_OBJECT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbGeneratorOutputTrackHeader", 1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbGeneratorOutput", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_MEMBER_REMOVED("skeleton", TYPE_OBJECT, "hkaSkeleton", 0)
	HK_PATCH_MEMBER_REMOVED("deleteTracks", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkaSkeleton", 2)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbGeneratorOutputTrackHeader", 1, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_MEMBER_REMOVED("numData", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("dataOffset", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("onFraction", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("id", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("type", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("isPoseAdditive", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbGeneratorOutputTracks", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_MEMBER_REMOVED("masterHeader", TYPE_STRUCT, "hkbGeneratorOutputTrackMasterHeader", 0)
	HK_PATCH_MEMBER_REMOVED("trackHeaders", TYPE_TUPLE_STRUCT, "hkbGeneratorOutputTrackHeader", 1)
	HK_PATCH_DEPENDS("hkbGeneratorOutputTrackHeader", 1)
	HK_PATCH_DEPENDS("hkbGeneratorOutputTrackMasterHeader", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbGeneratorOutputTrack", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkbGeneratorOutputConstTrack", HK_NULL)
	HK_PATCH_DEPENDS("hkbGeneratorOutputConstTrack", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbHandle", 0, "hkbHandle", 1)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
HK_PATCH_END()

HK_PATCH_BEGIN("hkbTarget", 1, "hkbTarget", 2)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
HK_PATCH_END()

HK_PATCH_BEGIN("hkbStateMachine", 1, "hkbStateMachine", 2)
	HK_PATCH_MEMBER_REMOVED("enableGlobalTransitions", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("enableNestedTransitions", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbFootIkModifier", 2, "hkbFootIkModifier", 3)
	HK_PATCH_MEMBER_ADDED_REAL("forwardAlignFraction", 1.0f)
	HK_PATCH_MEMBER_ADDED_REAL("sidewaysAlignFraction", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("sidewaysSampleWidth", 0.2f) // Changed from 0.2f
HK_PATCH_END()

HK_PATCH_BEGIN("hkbSimpleCharacter", 2, "hkbSimpleCharacter", 3)
	HK_PATCH_MEMBER_ADDED("behaviorGraph", TYPE_OBJECT, "hkbBehaviorGraph", 0)
	HK_PATCH_MEMBER_ADDED("projectData", TYPE_OBJECT, "hkbProjectData", 0)
	HK_PATCH_DEPENDS("hkbNode", 1)
	HK_PATCH_DEPENDS("hkbGenerator", 0)
	HK_PATCH_DEPENDS("hkbProjectData", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkbBehaviorGraph", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbBalanceControllerModifier", 1, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkbModifier", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("proportionalGain", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("derivativeGain", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("integralGain", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("checkBalanceModifier", TYPE_OBJECT, "hkbCheckBalanceModifier", 0)
	HK_PATCH_MEMBER_REMOVED("boneForces", TYPE_ARRAY_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("pelvisIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkbNode", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkbCheckBalanceModifier", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkbWorldFromModelModeData", 0)
	HK_PATCH_MEMBER_ADDED_INT("poseMatchingBone0", -1)
	HK_PATCH_MEMBER_ADDED_INT("poseMatchingBone1", -1)
	HK_PATCH_MEMBER_ADDED_INT("poseMatchingBone2", -1)
	HK_PATCH_MEMBER_ADDED_INT("mode", 3)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRagdollController", 0, "hkbRagdollController", 1)
	HK_PATCH_MEMBER_REMOVED("poseMatchingBone0", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("poseMatchingBone1", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("poseMatchingBone2", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("worldFromModelMode", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("worldFromModelModeData", TYPE_STRUCT, "hkbWorldFromModelModeData", 0)
	HK_PATCH_DEPENDS("hkbWorldFromModelModeData", 0)
	HK_PATCH_FUNCTION(hkbRagdollController_0_to_1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRagdollModifier", 1, "hkbRagdollModifier", 2)
	HK_PATCH_MEMBER_REMOVED("poseMatchingBone0", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("poseMatchingBone1", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("poseMatchingBone2", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("worldFromModelMode", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("worldFromModelModeData", TYPE_STRUCT, "hkbWorldFromModelModeData", 0)
	HK_PATCH_DEPENDS("hkbWorldFromModelModeData", 0)
	HK_PATCH_FUNCTION(hkbRagdollModifier_1_to_2)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbPoweredRagdollControlsModifier", 3, "hkbPoweredRagdollControlsModifier", 4)
	HK_PATCH_MEMBER_REMOVED("setTargetPose", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("poseMatchingBone0", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("poseMatchingBone1", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("poseMatchingBone2", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("worldFromModelMode", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("worldFromModelModeData", TYPE_STRUCT, "hkbWorldFromModelModeData", 0)
	HK_PATCH_DEPENDS("hkbWorldFromModelModeData", 0)
	HK_PATCH_FUNCTION(hkbPoweredRagdollControlsModifier_3_to_4)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRigidBodyRagdollControlsModifier", 2, "hkbRigidBodyRagdollControlsModifier", 3)
	HK_PATCH_MEMBER_REMOVED("setTargetPose", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRagdollModifier", 2, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkbModifier", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("poweredControlData", TYPE_STRUCT, "hkbPoweredRagdollControlData", 0)
	HK_PATCH_MEMBER_REMOVED("rigidBodyControlData", TYPE_STRUCT, "hkaKeyFrameHierarchyUtilityControlData", 0)
	HK_PATCH_MEMBER_REMOVED("poweredBoneWeights", TYPE_OBJECT, "hkbBoneWeightArray", 0)
	HK_PATCH_MEMBER_REMOVED("rigidBodyBoneWeights", TYPE_OBJECT, "hkbBoneWeightArray", 0)
	HK_PATCH_MEMBER_REMOVED("rigidBodyControllerBlendTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("enablePoweredController", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("enableRigidBodyController", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("setTargetPose", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("justSetTargetPose", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("worldFromModelModeData", TYPE_STRUCT, "hkbWorldFromModelModeData", 0)
	HK_PATCH_DEPENDS("hkbNode", 1)
	HK_PATCH_DEPENDS("hkaKeyFrameHierarchyUtilityControlData", 0)
	HK_PATCH_DEPENDS("hkbPoweredRagdollControlData", 0)
	HK_PATCH_DEPENDS("hkbWorldFromModelModeData", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkbBoneWeightArray", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRagdollDriverModifier", 3, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkbModifier", HK_NULL)
	HK_PATCH_DEPENDS("hkbNode", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkbModifier", 0)
	HK_PATCH_DEPENDS("hkbBindable", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRagdollController", 1, "hkbRagdollController", 2)
	HK_PATCH_MEMBER_REMOVED("rigidBodyControllerBlendTime", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacterStringData", 2, "hkbCharacterStringData", 3)
	HK_PATCH_MEMBER_ADDED("retargetingSkeletonMapperFilenames", TYPE_ARRAY_CSTRING, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacterSetup", 0, "hkbCharacterSetup", 1)
	HK_PATCH_MEMBER_ADDED("retargetingSkeletonMappers", TYPE_ARRAY_OBJECT, "hkaSkeletonMapper", 0)
	HK_PATCH_DEPENDS("hkaSkeletonMapper", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbPoweredRagdollControlsModifier", 4, "hkbPoweredRagdollControlsModifier", 5)
	HK_PATCH_MEMBER_ADDED("bones", TYPE_OBJECT, "hkbBoneIndexArray", 0)
	HK_PATCH_DEPENDS("hkbBoneIndexArray", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbRagdollController", 2, "hkbRagdollController", 3)
	HK_PATCH_MEMBER_ADDED("useAsynchronousStepping", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbGetUpModifier", 0, "hkbGetUpModifier", 1)
	HK_PATCH_MEMBER_ADDED("correctToGroundTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("surfaceNormal", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("surfacePosition", TYPE_VEC_4, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbDemoConfig", 1, "hkbDemoConfig", 2)
	HK_PATCH_MEMBER_RENAMED("stickVariables", "old_stickVariables")
	HK_PATCH_MEMBER_ADDED("stickVariables", TYPE_ARRAY_STRUCT, "hkbDemoConfigStickVariableInfo", 0)
	HK_PATCH_FUNCTION(hkbDemoConfig_1_to_2)
	HK_PATCH_MEMBER_REMOVED("old_stickVariables", TYPE_TUPLE_STRUCT, "hkbDemoConfigStickVariableInfo", 12)
	HK_PATCH_DEPENDS("hkbDemoConfigStickVariableInfo", 1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacterStringData", 3, "hkbCharacterStringData", 4)
	HK_PATCH_MEMBER_ADDED("lodNames", TYPE_ARRAY_CSTRING, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbCharacterData", 3, "hkbCharacterData", 4)
	HK_PATCH_MEMBER_ADDED("numBonesPerLod", TYPE_ARRAY_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkbPoseMatchingGenerator", 0, "hkbPoseMatchingGenerator", 1)
	HK_PATCH_MEMBER_ADDED_VEC_4_IDENTITY("worldFromModelRotation")
HK_PATCH_END()

HK_PATCH_BEGIN("hkbGetUpModifier", 1, "hkbGetUpModifier", 2)
	HK_PATCH_MEMBER_ADDED_VEC_4("groundNormal", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("alignWithGroundDuration", 0.000000f)
	HK_PATCH_FUNCTION(hkbGetUpModifier_1_to_2)
	HK_PATCH_MEMBER_REMOVED("correctToGroundTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("surfaceNormal", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("surfacePosition", TYPE_VEC_4, HK_NULL, 0)
HK_PATCH_END()

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20130718)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
