/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

// Destruction specific product patches applied before release 660.
// This file is #included by hkdPatches_Legacy.cpp

//=======
// 650b1
//=======

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdRemoveWeakConnectionsAction", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdAction")
	HK_PATCH_MEMBER_ADDED_REAL("minRelativeArea", 0.100000f)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdAction", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdRaycastGun", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkpFirstPersonGun")
	HK_PATCH_MEMBER_ADDED_REAL("destructionRadius", 0.600000f)
	HK_PATCH_MEMBER_ADDED("forceRadius", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_REAL("mass", 1000.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("velocity", 20.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("angImpulseFactor", 0.400000f)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkpFirstPersonGun", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdMissileGun", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkpProjectileGun")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkpFirstPersonGun", 0)
	HK_PATCH_DEPENDS("hkpProjectileGun", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdAction", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdFlexibleJointController", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdController")
	HK_PATCH_MEMBER_ADDED_REAL("activationStrength", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("inertiaMultiplier", 1.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("maxInertiaRatio", 10.000000f)
	HK_PATCH_MEMBER_ADDED_BYTE("connectToType", 1)
	HK_PATCH_MEMBER_ADDED("supportJoints", TYPE_STRUCT, "hkdFlexibleJointControllerJointDef", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdFlexibleJointControllerJointDef", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkdController", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdGrenadeGun", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkpProjectileGun")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkpFirstPersonGun", 0)
	HK_PATCH_DEPENDS("hkpProjectileGun", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdExplosionForceAction", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdAction")
	HK_PATCH_MEMBER_ADDED_VEC_4("explosionCenter", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("velocity", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("expandingVelocity", 20.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("virtMass", 1000.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("angularImpulseFactor", 0.200000f)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdAction", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdDebrisFracture", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdFracture")
	HK_PATCH_MEMBER_ADDED_REAL("gap", 0.000000f)
	HK_PATCH_MEMBER_ADDED("templateDebris", TYPE_OBJECT, "hkdBreakableShape", 0)
	HK_PATCH_DEPENDS("hkdFracture", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdBreakableShape", 1)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdFlexibleJointControllerJointDef", 0)
	HK_PATCH_MEMBER_ADDED_REAL("coneAngle", 20.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("twistAngle", 20.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("planeAngle", 3.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("relBendingStrength", 20.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("limitStiffness", 1.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("relBreakingStrength", 10.000000f)
	HK_PATCH_MEMBER_ADDED_BYTE("dropConstraintOnBreakage", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdSphereGun", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkpProjectileGun")
	HK_PATCH_MEMBER_ADDED("sphereGeometry", TYPE_OBJECT, "hkdGeometry", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdGeometry", 0)
	HK_PATCH_DEPENDS("hkpFirstPersonGun", 0)
	HK_PATCH_DEPENDS("hkpProjectileGun", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdVoronoiFracture", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdFracture")
	HK_PATCH_MEMBER_ADDED("splitPlaneGeometry", TYPE_OBJECT, "hkdGeometry", 0)
	HK_PATCH_MEMBER_ADDED("pivots", TYPE_ARRAY_VEC_4, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkdFracture", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdGeometry", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdStickyGun", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkpProjectileGun")
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkpFirstPersonGun", 0)
	HK_PATCH_DEPENDS("hkpProjectileGun", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdGrenadeGunBlueprint", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkdWeaponBlueprint", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("maxProjectiles", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("reloadTime", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdWeaponBlueprint", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdWeaponBlueprint", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkReferencedObject", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("name", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("keyboardKey", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdBallGunBlueprint", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkdWeaponBlueprint", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("bulletRadius", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("bulletVelocity", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("bulletMass", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("damageMultiplier", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("maxBulletsInWorld", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdWeaponBlueprint", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdCompoundBreakableBodyBlueprint", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkReferencedObject", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("attachToNearbyObjects", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("controller", TYPE_OBJECT, "hkdController", 0)
	HK_PATCH_MEMBER_REMOVED("groupName", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkdController", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdGravityGunBlueprint", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkdWeaponBlueprint", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("maxNumObjectsPicked", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("maxMassOfObjectPicked", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("maxDistOfObjectPicked", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("impulseAppliedWhenObjectNotPicked", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("throwVelocity", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("capturedObjectPosition", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("capturedObjectsOffset", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdWeaponBlueprint", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdChangeMassGunBlueprint", 0, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkdWeaponBlueprint", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("massChangeRatio", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("maxDistOfObjectPicked", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdWeaponBlueprint", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdBody", 0, "hkdBody", 1)
	HK_PATCH_MEMBER_REMOVED("findInitialContactPoints", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdBody", 1, "hkdBody", 2)
	HK_PATCH_MEMBER_ADDED("attributes", TYPE_ARRAY_STRUCT, "hkxAttribute", 0)
	HK_PATCH_DEPENDS("hkxAttribute", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdBreakableBodyBlueprint", 0, "hkdBreakableBodyBlueprint", 1)
	HK_PATCH_MEMBER_REMOVED("findInitialContactPoints", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdBreakableBody", 0, "hkdBreakableBody", 1)
	HK_PATCH_PARENT_SET("hkReferencedObject", "hkpBreakableBody")
	HK_PATCH_MEMBER_ADDED("properties", TYPE_STRUCT, "hkdProperties", 0)
	HK_PATCH_DEPENDS("hkdProperties", 0)
	HK_PATCH_DEPENDS("hkpBreakableBody", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdBreakableShape", 0, "hkdBreakableShape", 1)
	HK_PATCH_MEMBER_RENAMED("breakingPropogationRate", "breakingPropagationRate")
	HK_PATCH_MEMBER_ADDED_BYTE("flexibleJointType", 0)
	HK_PATCH_MEMBER_ADDED_BYTE("qualityType", 0)
	HK_PATCH_MEMBER_ADDED("properties", TYPE_STRUCT, "hkdProperties", 0)
	HK_PATCH_MEMBER_ADDED("actions", TYPE_ARRAY_OBJECT, "hkdAction", 0)
	HK_PATCH_MEMBER_ADDED_INT("userData", 0)
	HK_PATCH_DEPENDS("hkdProperties", 0)
	HK_PATCH_DEPENDS("hkdAction", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdWoodFracture", 0, "hkdWoodFracture", 1)
	HK_PATCH_MEMBER_RENAMED("flattenHierarchy", "old_flattenHierarchy")
	HK_PATCH_FUNCTION(hkdWoodFracture_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_flattenHierarchy", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkdFracture", 1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdWoodFracture", 1, "hkdWoodFracture", 2)
	HK_PATCH_DEPENDS("hkdWoodFractureSplittingData", 1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdWoodFractureSplittingData", 0, "hkdWoodFractureSplittingData", 1)
	HK_PATCH_MEMBER_ADDED_BYTE("rotateSplitGeom", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdShape", 0, "hkdShape", 1)
	HK_PATCH_MEMBER_RENAMED("breakingPropogationRate", "breakingPropagationRate")
	HK_PATCH_MEMBER_ADDED_BOOL("flattenChildCompounds", true)
	HK_PATCH_MEMBER_ADDED_BYTE("bodyQualityType", 0)
	HK_PATCH_MEMBER_ADDED_BYTE("flexibleJointType", 0)
	HK_PATCH_MEMBER_ADDED("attributes", TYPE_ARRAY_STRUCT, "hkxAttribute", 0)
	HK_PATCH_DEPENDS("hkxAttribute", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdSliceFracture", 0, "hkdSliceFracture", 1)
	HK_PATCH_MEMBER_RENAMED("childFracture", "old_childFracture")
	HK_PATCH_FUNCTION(hkdSliceFracture_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_childFracture", TYPE_OBJECT, "hkdFracture", 0)
	HK_PATCH_DEPENDS("hkdFracture", 1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdFracture", 0, "hkdFracture", 1)
	HK_PATCH_MEMBER_REMOVED("padding", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_BYTE("flattenHierarchy", 0)
	HK_PATCH_MEMBER_ADDED("childFracture", TYPE_OBJECT, "hkdFracture", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdSplitInHalfFracture", 0, "hkdSplitInHalfFracture", 1)
	HK_PATCH_MEMBER_RENAMED("flattenHierarchy", "old_flattenHierarchy")
	HK_PATCH_FUNCTION(hkdSplitInHalfFracture_0_to_1)
	HK_PATCH_MEMBER_REMOVED("old_flattenHierarchy", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkdFracture", 1)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdDeformationController", 0, "hkdDeformationController", 1)
	HK_PATCH_MEMBER_ADDED_REAL("strength", 0.000000f)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdDecorateFractureFaceActionFractureFaceInfo2", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdDecorateFractureFaceActionFractureFaceInfo")
	HK_PATCH_MEMBER_ADDED("maxSlope", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkdDecorateFractureFaceActionFractureFaceInfo", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdDecorateFractureFaceActionFractureFaceInfo", 0)
	HK_PATCH_MEMBER_ADDED("decorations", TYPE_OBJECT, "hkdBreakableShape", 0)
	HK_PATCH_MEMBER_ADDED_REAL("density", 1.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("gap", 0.000000f)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdBreakableShape", 1)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdDecorateFractureFaceAction", 0)
	HK_PATCH_MEMBER_ADDED_VEC_4("upDir", 0.000000f,1.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED("frontDir", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_REAL("vertGridDist", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("vertGridOffset", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("horGridDist", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("horGridOffset", 0.000000f)
	HK_PATCH_MEMBER_ADDED("top", TYPE_STRUCT, "hkdDecorateFractureFaceActionFractureFaceInfo2", 0)
	HK_PATCH_MEMBER_ADDED("bottom", TYPE_STRUCT, "hkdDecorateFractureFaceActionFractureFaceInfo2", 0)
	HK_PATCH_MEMBER_ADDED("right", TYPE_STRUCT, "hkdDecorateFractureFaceActionFractureFaceInfo", 0)
	HK_PATCH_MEMBER_ADDED("left", TYPE_STRUCT, "hkdDecorateFractureFaceActionFractureFaceInfo", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdDecorateFractureFaceActionFractureFaceInfo2", 0)
	HK_PATCH_DEPENDS("hkdDecorateFractureFaceActionFractureFaceInfo", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdFlexibleJointControllerJointDef", 0, "hkdFlexibleJointControllerJointDef", 1)
	HK_PATCH_MEMBER_ADDED_REAL("relPullingStrength", 1000.0f)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdDeformationController", 1, "hkdDeformationController", 2)
	HK_PATCH_MEMBER_ADDED_REAL("deformationRadius", 1.0f)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdVoronoiFracture", 0, "hkdVoronoiFracture", 1)
	HK_PATCH_MEMBER_ADDED_REAL("graphicsOverlap", 0.000000f)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdDecorateFractureFaceAction", 0, "hkdDecorateFractureFaceAction", 1)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdAction")
	HK_PATCH_MEMBER_ADDED_BYTE("decorationPivot", 1)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdCutOutFracture", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdFracture")
	HK_PATCH_MEMBER_ADDED("splitPlaneGeometry", TYPE_OBJECT, "hkdGeometry", 0)
	HK_PATCH_MEMBER_ADDED_REAL("expandShape", 0.001000f)
	HK_PATCH_MEMBER_ADDED("cutoutShapes", TYPE_ARRAY_OBJECT, "hkpEntity", 0)
	HK_PATCH_DEPENDS("hkpEntity", 1)
	HK_PATCH_DEPENDS("hkdFracture", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdGeometry", 0)
	HK_PATCH_DEPENDS("hkpWorldObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdShapeInstanceInfoRuntimeInfo", 0, "hkdShapeInstanceInfoRuntimeInfo", 1)
	HK_PATCH_MEMBER_REMOVED("oldChildIdx", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdDeformableBreakableShape", 0, "hkdDeformableBreakableShape", 1)
	HK_PATCH_MEMBER_ADDED("childKeys", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_FUNCTION(hkdDeformableBreakableShape_addChildKeys)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdDecomposeFracture", 1)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdFracture")
	HK_PATCH_MEMBER_ADDED("splittingGeometry", TYPE_OBJECT, "hkdGeometry", 0)
	HK_PATCH_MEMBER_ADDED_REAL("shiftToSmallerCrossSection", 0.100000f)
	HK_PATCH_MEMBER_ADDED_REAL("clipZoneWidth", 0.300000f)
	HK_PATCH_DEPENDS("hkdFracture", 1)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdGeometry", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdRemoveDebrisAction", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hkdAction")
        HK_PATCH_MEMBER_ADDED_REAL("removeInSeconds", 10.000000f)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hkdAction", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdBreakableShapeContactArea", 0)
	HK_PATCH_MEMBER_ADDED("vertices", TYPE_ARRAY_VEC_4, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdDebrisFracture", 0, "hkdDebrisFracture", 1)
		HK_PATCH_MEMBER_ADDED_BYTE("insertType", 2)
		HK_PATCH_MEMBER_ADDED_REAL("density", 1.0f)
		HK_PATCH_MEMBER_ADDED_INT("maxNumPieces", 100)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdBreakableShapeConnection", 0, "hkdBreakableShapeConnection",	   1)
		HK_PATCH_MEMBER_ADDED("contactAreaDetails", TYPE_OBJECT, "hkdBreakableShapeContactArea", 0)
		HK_PATCH_DEPENDS("hkdBreakableShapeContactArea", 0)
		HK_PATCH_FUNCTION(hkdBreakableShapeConnection_0_to_1)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdSetRigidBodyPropertiesAction", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdAction")
	HK_PATCH_MEMBER_ADDED_BYTE("setCollisionFilter", 0)
	HK_PATCH_MEMBER_ADDED_INT("collisionFilterInfo", 0)
	HK_PATCH_MEMBER_ADDED_BYTE("setDamping", 0)
	HK_PATCH_MEMBER_ADDED_REAL("linearDamping", 0.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("angularDamping", 0.500000f)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdAction", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdShockWaveAction", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdAction")
	HK_PATCH_MEMBER_ADDED("center", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED_REAL("initialRadius", 1.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("maxRadius", 100.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("thickness", 10.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("expandingVelocity", 30.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("damageMultiplier", 1.000000f)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdAction", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdSimpleShockWaveAction", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdShockWaveAction")
	HK_PATCH_MEMBER_ADDED_REAL("virtualMass", 100000.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("appliedVelocity", 100.000000f)
	HK_PATCH_MEMBER_ADDED_REAL("forceFallOff", 1.400000f)
	HK_PATCH_MEMBER_ADDED_REAL("relCounterForce", 0.500000f)
	HK_PATCH_DEPENDS("hkdShockWaveAction", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdAction", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdDestructionDemoConfig", 0, "hkdDestructionDemoConfig", 1)
	HK_PATCH_MEMBER_ADDED_BYTE("addFloor", 0)
	HK_PATCH_MEMBER_ADDED_INT("maxNumTimeoutDebrisPieces", (int)1000000)
	HK_PATCH_MEMBER_REMOVED("rotateLights", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdDestructionDemoConfig", 1, "hkdDestructionDemoConfig", 2)
	HK_PATCH_MEMBER_ADDED_BOOL("createSharedVertexBuffer", true)
	HK_PATCH_MEMBER_ADDED_BYTE("enableInstancing", 0)
	HK_PATCH_MEMBER_ADDED_INT("minNumTimeoutDebrisPieces", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdDestructionDemoConfig", 2, "hkdDestructionDemoConfig", 3)
	HK_PATCH_MEMBER_ADDED_BYTE("enableSSAO", 0)
	HK_PATCH_MEMBER_ADDED_BYTE("enableBloom", 0)
	HK_PATCH_MEMBER_ADDED_REAL("fogDensity", 0.000000f)
	HK_PATCH_MEMBER_ADDED_CSTRING("skyBoxName", HK_NULL)
	HK_PATCH_MEMBER_ADDED_VEC_4("initialCharacterDirection", 0.0f, 0.0f, 1.0f, 0.0f)
	HK_PATCH_MEMBER_ADDED_VEC_4("lightFillColor", 0.3f, 0.3f, 0.3f, 1.0f)
	HK_PATCH_MEMBER_ADDED_VEC_4("lightRimColor", 0.2f, 0.2f, 0.2f, 1.0f)
	HK_PATCH_MEMBER_ADDED_VEC_4("clearColor", 0.53f,0.55f,0.61f, 1.0f)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdBreakableBodyMemento", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkReferencedObject")
	HK_PATCH_MEMBER_ADDED_INT("bodyId", 65535)
	HK_PATCH_MEMBER_ADDED_VEC_4("rotation", 0.000000f,0.000000f,0.000000f,1.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("translation", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("linearVelocity", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_MEMBER_ADDED_VEC_4("angularVelocity", 0.000000f,0.000000f,0.000000f,0.000000f)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdSimpleBreakableBodyMemento", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdBreakableBodyMemento")
	HK_PATCH_MEMBER_ADDED("path", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkdBreakableBodyMemento", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdDeformableBreakableBodyMemento", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdBreakableBodyMemento")
	HK_PATCH_MEMBER_ADDED("shapeIndices", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("transforms", TYPE_ARRAY_VEC_16, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkdBreakableBodyMemento", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hkdCompoundBreakableBodyMemento", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hkdBreakableBodyMemento")
	HK_PATCH_MEMBER_ADDED("paths", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("transforms", TYPE_ARRAY_VEC_16, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkdBreakableBodyMemento", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdBreakableBodyBlueprint", 1, HK_NULL, HK_CLASS_REMOVED)
	HK_PATCH_PARENT_SET("hkReferencedObject", HK_NULL)
	HK_PATCH_MEMBER_REMOVED("rigidBodyName", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("compoundId", TYPE_CSTRING, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("fracture", TYPE_OBJECT, "hkdFracture", 0)
	HK_PATCH_MEMBER_REMOVED("dynamicFracture", TYPE_OBJECT, "hkdFracture", 0)
	HK_PATCH_MEMBER_REMOVED("controller", TYPE_OBJECT, "hkdController", 0)
	HK_PATCH_MEMBER_REMOVED("strength", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("relativeSubpieceStrength", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("breakingPropogationRate", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("attachToNearbyObjects", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("mergeCoplanarTriangles", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_REMOVED("destructionRadius", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkdFracture", 1)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
	HK_PATCH_DEPENDS("hkdController", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdShape", 1, "hkdShape", 2)
	HK_PATCH_FUNCTION(hkdShape_1_to_2)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdRemoveDebrisAction", 0, "hkdRemoveDebrisAction", 1)
	HK_PATCH_MEMBER_ADDED_BYTE("removeOnTimeout", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hkdShapeInstanceInfoRuntimeInfo", 1, "hkdShapeInstanceInfoRuntimeInfo", 2)
	HK_PATCH_MEMBER_ADDED("parentUid", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20130718)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
