/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

#include "Reflections/hkpCachingShapePhantomReflection.cpp"
#include "Reflections/hkpRigidBodyReflection.cpp"
#include "Reflections/hkpListShapeBreakableMaterialReflection.cpp"
#include "Reflections/hkpSimulationReflection.cpp"
#include "Reflections/hkpConstraintChainInstanceActionReflection.cpp"
#include "Reflections/hkpConstraintInstanceReflection.cpp"
#include "Reflections/hkpFixedRigidMotionReflection.cpp"
#include "Reflections/hkpWorldObjectReflection.cpp"
#include "Reflections/hkpConstraintChainInstanceReflection.cpp"
#include "Reflections/hkpModifierConstraintAtomReflection.cpp"
#include "Reflections/hkpArrayActionReflection.cpp"
#include "Reflections/hkpBreakableMultiMaterialReflection.cpp"
#include "Reflections/hkpKeyframedRigidMotionReflection.cpp"
#include "Reflections/hkpGenericConstraintDataReflection.cpp"
#include "Reflections/hkpBallSocketChainDataReflection.cpp"
#include "Reflections/hkpConstraintChainDataReflection.cpp"
#include "Reflections/hkpBinaryActionReflection.cpp"
#include "Reflections/hkpPhysicsSystemReflection.cpp"
#include "Reflections/hkpDefaultWorldMemoryWatchDogReflection.cpp"
#include "Reflections/hkpThinBoxMotionReflection.cpp"
#include "Reflections/hkpAabbPhantomReflection.cpp"
#include "Reflections/hkpMotionReflection.cpp"
#include "Reflections/hkpUnaryActionReflection.cpp"
#include "Reflections/hkpMalleableConstraintDataReflection.cpp"
#include "Reflections/hkpScsBreakableMaterialReflection.cpp"
#include "Reflections/hkpActionReflection.cpp"
#include "Reflections/hkpShapePhantomReflection.cpp"
#include "Reflections/hkpWorldCinfoReflection.cpp"
#include "Reflections/hkpWorldReflection.cpp"
#include "Reflections/hkpBoxMotionReflection.cpp"
#include "Reflections/hkpSimpleBreakableMaterialReflection.cpp"
#include "Reflections/hkpBreakableShapeReflection.cpp"
#include "Reflections/hkpEntityReflection.cpp"
#include "Reflections/hkpCharacterMotionReflection.cpp"
#include "Reflections/hkpMaterialReflection.cpp"
#include "Reflections/hkpGenericConstraintSchemeReflection.cpp"
#include "Reflections/hkpEmsBreakableMaterialReflection.cpp"
#include "Reflections/hkpWorldMemoryAvailableWatchDogReflection.cpp"
#include "Reflections/hkpBreakableMaterialReflection.cpp"
#include "Reflections/hkpSimpleShapePhantomReflection.cpp"
#include "Reflections/hkpStiffSpringChainDataReflection.cpp"
#include "Reflections/hkpPhantomReflection.cpp"
#include "Reflections/hkpBreakableConstraintDataReflection.cpp"
#include "Reflections/hkpConstraintCollisionFilterReflection.cpp"
#include "Reflections/hkpSimpleContactConstraintAtomReflection.cpp"
#include "Reflections/hkpSphereMotionReflection.cpp"
#include "Reflections/hkpPairCollisionFilterReflection.cpp"
#include "Reflections/hkpBreakableBodyReflection.cpp"
#ifndef HK_EXCLUDE_FEATURE_hkpPoweredChainData
#include "Reflections/hkpPoweredChainDatahkpPoweredChainDataReflection.cpp"
#endif

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20130718)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
