/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

// Cloth specific product patches applied to release 2010_1.
// This file is #included by hclPatches_2010_1.cpp

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBendStiffnessConstraintSetMxBatch",0)
		HK_PATCH_MEMBER_ADDED("weightsA", TYPE_TUPLE_REAL, HK_NULL, 16)
		HK_PATCH_MEMBER_ADDED("weightsB", TYPE_TUPLE_REAL, HK_NULL, 16)
		HK_PATCH_MEMBER_ADDED("weightsC", TYPE_TUPLE_REAL, HK_NULL, 16)
		HK_PATCH_MEMBER_ADDED("weightsD", TYPE_TUPLE_REAL, HK_NULL, 16)
		HK_PATCH_MEMBER_ADDED("bendStiffnesses", TYPE_TUPLE_REAL, HK_NULL, 16)
		HK_PATCH_MEMBER_ADDED("restCurvatures", TYPE_TUPLE_REAL, HK_NULL, 16)
		HK_PATCH_MEMBER_ADDED("invMassesA", TYPE_TUPLE_REAL, HK_NULL, 16)
		HK_PATCH_MEMBER_ADDED("invMassesB", TYPE_TUPLE_REAL, HK_NULL, 16)
		HK_PATCH_MEMBER_ADDED("invMassesC", TYPE_TUPLE_REAL, HK_NULL, 16)
		HK_PATCH_MEMBER_ADDED("invMassesD", TYPE_TUPLE_REAL, HK_NULL, 16)
		HK_PATCH_MEMBER_ADDED("particlesA", TYPE_TUPLE_INT, HK_NULL, 16)
		HK_PATCH_MEMBER_ADDED("particlesB", TYPE_TUPLE_INT, HK_NULL, 16)
		HK_PATCH_MEMBER_ADDED("particlesC", TYPE_TUPLE_INT, HK_NULL, 16)
		HK_PATCH_MEMBER_ADDED("particlesD", TYPE_TUPLE_INT, HK_NULL, 16)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBendStiffnessConstraintSetMx", 0)
		HK_PATCH_PARENT_SET(HK_NULL, "hclConstraintSet")
		HK_PATCH_MEMBER_ADDED("batches", TYPE_ARRAY_STRUCT, "hclBendStiffnessConstraintSetMxBatch", 0)
		HK_PATCH_MEMBER_ADDED("singles", TYPE_ARRAY_STRUCT, "hclBendStiffnessConstraintSetMxSingle", 0)
		HK_PATCH_MEMBER_ADDED("useRestPoseConfig", TYPE_BYTE, HK_NULL, 0)
		HK_PATCH_DEPENDS("hkBaseObject", 0)
		HK_PATCH_DEPENDS("hclConstraintSet", 0)
		HK_PATCH_DEPENDS("hclBendStiffnessConstraintSetMxSingle", 0)
		HK_PATCH_DEPENDS("hkReferencedObject", 0)
		HK_PATCH_DEPENDS("hclBendStiffnessConstraintSetMxBatch", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBendStiffnessConstraintSetMxSingle",0)
		HK_PATCH_MEMBER_ADDED("weightA", TYPE_REAL, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("weightB", TYPE_REAL, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("weightC", TYPE_REAL, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("weightD", TYPE_REAL, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("bendStiffness", TYPE_REAL, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("restCurvature", TYPE_REAL, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("invMassA", TYPE_REAL, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("invMassB", TYPE_REAL, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("invMassC", TYPE_REAL, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("invMassD", TYPE_REAL, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("particleA", TYPE_INT, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("particleB", TYPE_INT, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("particleC", TYPE_INT, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("particleD", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclVolumeConstraintMxApplySingleData",0)
	   HK_PATCH_MEMBER_ADDED("frameVector", TYPE_VEC_4, HK_NULL, 0)
	   HK_PATCH_MEMBER_ADDED("particleIndex", TYPE_INT, HK_NULL, 0)
	   HK_PATCH_MEMBER_ADDED("stiffness", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclVolumeConstraintMx", 0)
	   HK_PATCH_PARENT_SET(HK_NULL, "hclConstraintSet")
	   HK_PATCH_MEMBER_ADDED("frameBatchDatas", TYPE_ARRAY_STRUCT, "hclVolumeConstraintMxFrameBatchData", 0)
	   HK_PATCH_MEMBER_ADDED("frameSingleDatas", TYPE_ARRAY_STRUCT, "hclVolumeConstraintMxFrameSingleData", 0)
	   HK_PATCH_MEMBER_ADDED("applyBatchDatas", TYPE_ARRAY_STRUCT, "hclVolumeConstraintMxApplyBatchData", 0)
	   HK_PATCH_MEMBER_ADDED("applySingleDatas", TYPE_ARRAY_STRUCT, "hclVolumeConstraintMxApplySingleData", 0)
	   HK_PATCH_DEPENDS("hkBaseObject", 0)
	   HK_PATCH_DEPENDS("hclConstraintSet", 0)
	   HK_PATCH_DEPENDS("hclVolumeConstraintMxApplyBatchData", 0)
	   HK_PATCH_DEPENDS("hclVolumeConstraintMxFrameBatchData", 0)
	   HK_PATCH_DEPENDS("hkReferencedObject", 0)
	   HK_PATCH_DEPENDS("hclVolumeConstraintMxFrameSingleData", 0)
	   HK_PATCH_DEPENDS("hclVolumeConstraintMxApplySingleData", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclVolumeConstraintMxApplyBatchData", 0)
	   HK_PATCH_MEMBER_ADDED("frameVector", TYPE_TUPLE_VEC_4, HK_NULL, 16)
	   HK_PATCH_MEMBER_ADDED("particleIndex", TYPE_TUPLE_INT, HK_NULL, 16)
	   HK_PATCH_MEMBER_ADDED("stiffness", TYPE_TUPLE_REAL, HK_NULL, 16)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclVolumeConstraintMxFrameBatchData", 0)
	   HK_PATCH_MEMBER_ADDED("frameVector", TYPE_TUPLE_VEC_4, HK_NULL, 16)
	   HK_PATCH_MEMBER_ADDED("particleIndex", TYPE_TUPLE_INT, HK_NULL, 16)
	   HK_PATCH_MEMBER_ADDED("weight", TYPE_TUPLE_REAL, HK_NULL, 16)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclVolumeConstraintMxFrameSingleData",0)
	   HK_PATCH_MEMBER_ADDED("frameVector", TYPE_VEC_4, HK_NULL, 0)
	   HK_PATCH_MEMBER_ADDED("particleIndex", TYPE_INT, HK_NULL, 0)
	   HK_PATCH_MEMBER_ADDED("weight", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclMeshBoneDeformOperatorTriangleBonePair", 0)
		HK_PATCH_MEMBER_ADDED("localBoneTransform", TYPE_VEC_16, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("triangleIndex", TYPE_INT, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("weight", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclMeshBoneDeformSetupObject", 0)
		HK_PATCH_PARENT_SET(HK_NULL, "hclOperatorSetupObject")
		HK_PATCH_MEMBER_ADDED("name", TYPE_CSTRING, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("inputBufferSetupObject", TYPE_OBJECT, "hclBufferSetupObject", 0)
		HK_PATCH_MEMBER_ADDED("inputTriangleSelection", TYPE_STRUCT, "hclTriangleSelectionInput", 0)
		HK_PATCH_MEMBER_ADDED("outputTransformSetSetupObject", TYPE_OBJECT, "hclTransformSetSetupObject", 0)
		HK_PATCH_MEMBER_ADDED("deformedBones", TYPE_ARRAY_CSTRING, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("maxTrianglesPerBone", TYPE_INT, HK_NULL, 0)
		HK_PATCH_MEMBER_ADDED("minimumTriangleWeight", TYPE_REAL, HK_NULL, 0)
		HK_PATCH_DEPENDS("hkBaseObject", 0)
		HK_PATCH_DEPENDS("hclTransformSetSetupObject", 0)
		HK_PATCH_DEPENDS("hclOperatorSetupObject", 0)
		HK_PATCH_DEPENDS("hclTriangleSelectionInput", 0)
		HK_PATCH_DEPENDS("hkReferencedObject", 0)
		HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclMeshBoneDeformOperator", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hclOperator")
	HK_PATCH_MEMBER_ADDED("inputBufferIdx", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("outputTransformSetIdx", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("triangleBonePairs", TYPE_ARRAY_STRUCT, "hclMeshBoneDeformOperatorTriangleBonePair", 0)
	HK_PATCH_MEMBER_ADDED("triangleBoneStartForBone", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hclMeshBoneDeformOperatorTriangleBonePair", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hclOperator", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSimpleMeshBoneDeformOperator", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hclOperator")
	HK_PATCH_MEMBER_ADDED("inputBufferIdx", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("outputTransformSetIdx", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("triangleBonePairs", TYPE_ARRAY_STRUCT, "hclSimpleMeshBoneDeformOperatorTriangleBonePair", 0)
	HK_PATCH_MEMBER_ADDED("localBoneTransforms", TYPE_ARRAY_VEC_16, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hclSimpleMeshBoneDeformOperatorTriangleBonePair", 0)
	HK_PATCH_DEPENDS("hclOperator", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSimpleMeshBoneDeformOperatorTriangleBonePair", 0)
	HK_PATCH_MEMBER_ADDED("boneOffset", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("triangleOffset", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclAntiPinchConstraintSetPerParticle", 1)
	HK_PATCH_MEMBER_ADDED("particleIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("referenceVertex", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclAntiPinchConstraintSet", 1)
	HK_PATCH_PARENT_SET(HK_NULL, "hclConstraintSet")
	HK_PATCH_MEMBER_ADDED("perParticleData", TYPE_ARRAY_STRUCT, "hclAntiPinchConstraintSetPerParticle", 0)
	HK_PATCH_MEMBER_ADDED("toAnimPeriod", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("toSimPeriod", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("toSimMaxDistance", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("referenceMeshBufferIdx", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hclConstraintSet", 0)
	HK_PATCH_DEPENDS("hclAntiPinchConstraintSetPerParticle", 1)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclSimClothDataCollidablePinchingData", 0)
	HK_PATCH_MEMBER_ADDED("pinchDetectionEnabled", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pinchDetectionPriority", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pinchDetectionRadius", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSimClothSetupObjectPerInstanceCollidable", 1, "hclSimClothSetupObjectPerInstanceCollidable", 2)
	HK_PATCH_MEMBER_ADDED("pinchDetectionEnabled", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pinchDetectionPriority", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pinchDetectionRadius", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclCollidable", 1, "hclCollidable", 2)
	HK_PATCH_MEMBER_ADDED("pinchDetectionEnabled", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pinchDetectionPriority", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pinchDetectionRadius", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSimClothSetupObject", 2, "hclSimClothSetupObject", 3)
	HK_PATCH_MEMBER_ADDED("enablePinchDetection", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pinchDetectionEnabledParticles", TYPE_STRUCT, "hclVertexSelectionInput", 0)
	HK_PATCH_MEMBER_ADDED("toAnimPeriod", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("toSimPeriod", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("drivePinchedParticlesToReferenceMesh", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pinchReferenceBufferSetup", TYPE_OBJECT, "hclBufferSetupObject", 0)
	HK_PATCH_DEPENDS("hclVertexSelectionInput", 0)
	HK_PATCH_DEPENDS("hclBufferSetupObject", 0)
	HK_PATCH_FUNCTION(hclSimClothSetupObject_2_to_3)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSimClothDataParticleData", 0, "hclSimClothDataParticleData", 1)
	HK_PATCH_MEMBER_ADDED("pinchDetectionEnabled", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSimClothData", 4, "hclSimClothData", 5)
	HK_PATCH_MEMBER_ADDED("antiPinchConstraintSets", TYPE_ARRAY_OBJECT, "hclConstraintSet", 0)
	HK_PATCH_MEMBER_ADDED("pinchDetectionEnabled", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("collidablePinchingDatas", TYPE_ARRAY_STRUCT, "hclSimClothDataCollidablePinchingData", 0)
	HK_PATCH_DEPENDS("hclSimClothDataCollidablePinchingData", 0)
	HK_PATCH_DEPENDS("hclConstraintSet", 0)
	HK_PATCH_FUNCTION(hclSimClothData_4_to_5)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSimClothData", 5, "hclSimClothData", 6)
	HK_PATCH_MEMBER_ADDED("minPinchedParticleIndex", TYPE_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("maxPinchedParticleIndex", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSimClothSetupObjectPerInstanceCollidable", 2, "hclSimClothSetupObjectPerInstanceCollidable", 3)
	HK_PATCH_MEMBER_REMOVED("pinchDetectionPriority", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pinchDetectionPriority", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclCollidable", 2, "hclCollidable", 3)
	HK_PATCH_MEMBER_REMOVED("pinchDetectionPriority", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pinchDetectionPriority", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSimClothDataCollidablePinchingData", 0, "hclSimClothDataCollidablePinchingData", 1)
	HK_PATCH_MEMBER_REMOVED("pinchDetectionPriority", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("pinchDetectionPriority", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSimClothDataParticleData", 1, "hclSimClothDataParticleData", 2)
	HK_PATCH_MEMBER_REMOVED("pinchDetectionEnabled", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSimClothData", 6, "hclSimClothData", 7)
	HK_PATCH_MEMBER_ADDED("perParticlePinchDetectionEnabledFlags", TYPE_ARRAY_BYTE, HK_NULL, 0)
	HK_PATCH_FUNCTION(hclSimClothData_6_to_7)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSkinOperator", 2, "hclSkinOperator", 3)
	HK_PATCH_MEMBER_ADDED("usedBoneGroupIds", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("boneGroupSize", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSkinOperatorBoneInfluence", 0, "hclSkinOperatorBoneInfluence", 1)
   HK_PATCH_MEMBER_RENAMED("boneIndex", "old_boneIndex")
   HK_PATCH_MEMBER_ADDED("boneIndex", TYPE_INT, HK_NULL, 0)
   HK_PATCH_FUNCTION(hclSkinOperatorBoneInfluence_0_to_1)
   HK_PATCH_MEMBER_REMOVED("old_boneIndex", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBufferLayout", 0)
    HK_PATCH_MEMBER_ADDED("elementsLayout", TYPE_TUPLE_STRUCT, "hclBufferLayoutBufferElement", 4)
    HK_PATCH_MEMBER_ADDED("numSlots", TYPE_BYTE, HK_NULL, 0)
    HK_PATCH_MEMBER_ADDED("slots", TYPE_TUPLE_STRUCT, "hclBufferLayoutSlot", 4)
    HK_PATCH_MEMBER_ADDED("triangleFormat", TYPE_BYTE, HK_NULL, 0)
    HK_PATCH_DEPENDS("hclBufferLayoutBufferElement", 0)
    HK_PATCH_DEPENDS("hclBufferLayoutSlot", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBufferLayoutBufferElement", 0)
    HK_PATCH_MEMBER_ADDED("vectorConversion", TYPE_BYTE, HK_NULL, 0)
    HK_PATCH_MEMBER_ADDED("vectorSize", TYPE_BYTE, HK_NULL, 0)
    HK_PATCH_MEMBER_ADDED("slotId", TYPE_BYTE, HK_NULL, 0)
    HK_PATCH_MEMBER_ADDED("slotStart", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBufferLayoutSlot", 0)
    HK_PATCH_MEMBER_ADDED("flags", TYPE_BYTE, HK_NULL, 0)
    HK_PATCH_MEMBER_ADDED("stride", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclBufferDefinition", 0, "hclBufferDefinition", 1)
    HK_PATCH_MEMBER_ADDED("bufferLayout", TYPE_STRUCT, "hclBufferLayout", 0)

    HK_PATCH_DEPENDS("hclBufferLayout", 0)
    HK_PATCH_FUNCTION(hclBufferDefinition_0_to_1)
HK_PATCH_END()

HK_PATCH_BEGIN("hclStorageSetupMesh", 0, "hclStorageSetupMesh", 1)
	HK_PATCH_MEMBER_REMOVED("mode", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclLocalRangeSetupObject", 0, "hclLocalRangeSetupObject", 1)
	HK_PATCH_MEMBER_ADDED("useMinNormalDistance", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("useMaxNormalDistance", TYPE_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("stiffness", TYPE_REAL, HK_NULL, 0)
	HK_PATCH_FUNCTION(hclLocalRangeSetupObject_0_to_1)
HK_PATCH_END()

HK_PATCH_BEGIN("hclLocalRangeConstraintSet", 1, "hclLocalRangeConstraintSet", 2)
	HK_PATCH_MEMBER_ADDED("stiffness", TYPE_REAL, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclObjectSpaceDeformerTwoBlendEntryBlock", 0)
    HK_PATCH_MEMBER_ADDED("vertexIndices", TYPE_TUPLE_INT, HK_NULL, 16)
    HK_PATCH_MEMBER_ADDED("boneIndices", TYPE_TUPLE_INT, HK_NULL, 32)
    HK_PATCH_MEMBER_ADDED("boneWeights", TYPE_TUPLE_BYTE, HK_NULL, 32)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBoneSpaceSkinOperator", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclOperator")
        HK_PATCH_MEMBER_ADDED("outputBufferIndex", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("transformSetIndex", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("boneSpaceDeformer", TYPE_STRUCT, "hclBoneSpaceDeformer", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclBoneSpaceDeformer", 0)
        HK_PATCH_DEPENDS("hclOperator", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclObjectSpaceSkinPNOperator", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclObjectSpaceSkinOperator")
        HK_PATCH_MEMBER_ADDED("localPNs", TYPE_ARRAY_STRUCT, "hclObjectSpaceDeformerLocalBlockPN", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclOperator", 0)
        HK_PATCH_DEPENDS("hclObjectSpaceSkinOperator", 0)
        HK_PATCH_DEPENDS("hclObjectSpaceDeformerLocalBlockPN", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBoneSpaceDeformerThreeBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("vertexIndices", TYPE_TUPLE_INT, HK_NULL, 5)
        HK_PATCH_MEMBER_ADDED("boneIndices", TYPE_TUPLE_INT, HK_NULL, 15)
        HK_PATCH_MEMBER_ADDED("padding", TYPE_TUPLE_BYTE, HK_NULL, 8)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBoneSpaceDeformerFourBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("vertexIndices", TYPE_TUPLE_INT, HK_NULL, 4)
        HK_PATCH_MEMBER_ADDED("boneIndices", TYPE_TUPLE_INT, HK_NULL, 16)
        HK_PATCH_MEMBER_ADDED("padding", TYPE_TUPLE_BYTE, HK_NULL, 8)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclObjectSpaceDeformer", 0)
        HK_PATCH_MEMBER_ADDED("fourBlendEntries", TYPE_ARRAY_STRUCT, "hclObjectSpaceDeformerFourBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("threeBlendEntries", TYPE_ARRAY_STRUCT, "hclObjectSpaceDeformerThreeBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("twoBlendEntries", TYPE_ARRAY_STRUCT, "hclObjectSpaceDeformerTwoBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("oneBlendEntries", TYPE_ARRAY_STRUCT, "hclObjectSpaceDeformerOneBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("controlBytes", TYPE_ARRAY_BYTE, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("startVertexIndex", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("endVertexIndex", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("batchSizeSpu", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("partialWrite", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_DEPENDS("hclObjectSpaceDeformerThreeBlendEntryBlock", 0)
        HK_PATCH_DEPENDS("hclObjectSpaceDeformerTwoBlendEntryBlock", 0)
        HK_PATCH_DEPENDS("hclObjectSpaceDeformerFourBlendEntryBlock", 0)
        HK_PATCH_DEPENDS("hclObjectSpaceDeformerOneBlendEntryBlock", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBoneSpaceDeformerOneBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("vertexIndices", TYPE_TUPLE_INT, HK_NULL, 16)
        HK_PATCH_MEMBER_ADDED("boneIndices", TYPE_TUPLE_INT, HK_NULL, 16)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclObjectSpaceDeformerThreeBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("vertexIndices", TYPE_TUPLE_INT, HK_NULL, 16)
        HK_PATCH_MEMBER_ADDED("boneIndices", TYPE_TUPLE_INT, HK_NULL, 48)
        HK_PATCH_MEMBER_ADDED("boneWeights", TYPE_TUPLE_BYTE, HK_NULL, 48)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBoneSpaceSkinPOperator", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclBoneSpaceSkinOperator")
        HK_PATCH_MEMBER_ADDED("localPs", TYPE_ARRAY_STRUCT, "hclBoneSpaceDeformerLocalBlockP", 0)
        HK_PATCH_DEPENDS("hclBoneSpaceSkinOperator", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclOperator", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclBoneSpaceDeformerLocalBlockP", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclObjectSpaceDeformerFourBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("vertexIndices", TYPE_TUPLE_INT, HK_NULL, 16)
        HK_PATCH_MEMBER_ADDED("boneIndices", TYPE_TUPLE_INT, HK_NULL, 64)
        HK_PATCH_MEMBER_ADDED("boneWeights", TYPE_TUPLE_BYTE, HK_NULL, 64)
HK_PATCH_END()


HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBoneSpaceDeformerTwoBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("vertexIndices", TYPE_TUPLE_INT, HK_NULL, 8)
        HK_PATCH_MEMBER_ADDED("boneIndices", TYPE_TUPLE_INT, HK_NULL, 16)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBoneSpaceSkinPNOperator", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclBoneSpaceSkinOperator")
        HK_PATCH_MEMBER_ADDED("localPNs", TYPE_ARRAY_STRUCT, "hclBoneSpaceDeformerLocalBlockPN", 0)
        HK_PATCH_DEPENDS("hclBoneSpaceSkinOperator", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclBoneSpaceDeformerLocalBlockPN", 0)
        HK_PATCH_DEPENDS("hclOperator", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBoneSpaceSkinPNTOperator", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclBoneSpaceSkinOperator")
        HK_PATCH_MEMBER_ADDED("localPNTs", TYPE_ARRAY_STRUCT, "hclBoneSpaceDeformerLocalBlockPNT", 0)
        HK_PATCH_DEPENDS("hclBoneSpaceDeformerLocalBlockPNT", 0)
        HK_PATCH_DEPENDS("hclBoneSpaceSkinOperator", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclOperator", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBoneSpaceSkinPNTBOperator", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclBoneSpaceSkinOperator")
        HK_PATCH_MEMBER_ADDED("localPNTBs", TYPE_ARRAY_STRUCT, "hclBoneSpaceDeformerLocalBlockPNTB", 0)
        HK_PATCH_DEPENDS("hclBoneSpaceDeformerLocalBlockPNTB", 0)
        HK_PATCH_DEPENDS("hclBoneSpaceSkinOperator", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclOperator", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclBoneSpaceDeformer", 0)
        HK_PATCH_MEMBER_ADDED("fourBlendEntries", TYPE_ARRAY_STRUCT, "hclBoneSpaceDeformerFourBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("threeBlendEntries", TYPE_ARRAY_STRUCT, "hclBoneSpaceDeformerThreeBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("twoBlendEntries", TYPE_ARRAY_STRUCT, "hclBoneSpaceDeformerTwoBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("oneBlendEntries", TYPE_ARRAY_STRUCT, "hclBoneSpaceDeformerOneBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("controlBytes", TYPE_ARRAY_BYTE, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("startVertexIndex", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("endVertexIndex", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("batchSizeSpu", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("partialWrite", TYPE_BYTE, HK_NULL, 0)
        HK_PATCH_DEPENDS("hclBoneSpaceDeformerThreeBlendEntryBlock", 0)
        HK_PATCH_DEPENDS("hclBoneSpaceDeformerFourBlendEntryBlock", 0)
        HK_PATCH_DEPENDS("hclBoneSpaceDeformerTwoBlendEntryBlock", 0)
        HK_PATCH_DEPENDS("hclBoneSpaceDeformerOneBlendEntryBlock", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclObjectSpaceDeformerOneBlendEntryBlock", 0)
        HK_PATCH_MEMBER_ADDED("vertexIndices", TYPE_TUPLE_INT, HK_NULL, 16)
        HK_PATCH_MEMBER_ADDED("boneIndices", TYPE_TUPLE_INT, HK_NULL, 16)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclObjectSpaceSkinPNTBOperator", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclObjectSpaceSkinOperator")
        HK_PATCH_MEMBER_ADDED("localPNTBs", TYPE_ARRAY_STRUCT, "hclObjectSpaceDeformerLocalBlockPNTB", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclOperator", 0)
        HK_PATCH_DEPENDS("hclObjectSpaceDeformerLocalBlockPNTB", 0)
        HK_PATCH_DEPENDS("hclObjectSpaceSkinOperator", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclObjectSpaceSkinOperator", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclOperator")
        HK_PATCH_MEMBER_ADDED("outputBufferIndex", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("transformSetIndex", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("boneFromSkinMeshTransforms", TYPE_ARRAY_VEC_16, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("objectSpaceDeformer", TYPE_STRUCT, "hclObjectSpaceDeformer", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclOperator", 0)
        HK_PATCH_DEPENDS("hclObjectSpaceDeformer", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclObjectSpaceSkinPOperator", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclObjectSpaceSkinOperator")
        HK_PATCH_MEMBER_ADDED("localPs", TYPE_ARRAY_STRUCT, "hclObjectSpaceDeformerLocalBlockP", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclOperator", 0)
        HK_PATCH_DEPENDS("hclObjectSpaceDeformerLocalBlockP", 0)
        HK_PATCH_DEPENDS("hclObjectSpaceSkinOperator", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclObjectSpaceSkinPNTOperator", 0)
        HK_PATCH_PARENT_SET(HK_NULL, "hclObjectSpaceSkinOperator")
        HK_PATCH_MEMBER_ADDED("localPNTs", TYPE_ARRAY_STRUCT, "hclObjectSpaceDeformerLocalBlockPNT", 0)
        HK_PATCH_DEPENDS("hkBaseObject", 0)
        HK_PATCH_DEPENDS("hclOperator", 0)
        HK_PATCH_DEPENDS("hclObjectSpaceSkinOperator", 0)
        HK_PATCH_DEPENDS("hkReferencedObject", 0)
        HK_PATCH_DEPENDS("hclObjectSpaceDeformerLocalBlockPNT", 0)
HK_PATCH_END()


HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclClothStateTransformSetAccess", 0)
        HK_PATCH_MEMBER_ADDED("transformSetIndex", TYPE_INT, HK_NULL, 0)
        HK_PATCH_MEMBER_ADDED("transformSetUsage", TYPE_STRUCT, "hclTransformSetUsage", 0)
        HK_PATCH_DEPENDS("hclTransformSetUsage", 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclTransformSetUsage", 0)
        HK_PATCH_MEMBER_ADDED("perComponentFlags", TYPE_TUPLE_BYTE, HK_NULL, 2)
HK_PATCH_END()

HK_PATCH_BEGIN("hclClothState", 0, "hclClothState", 1)
		HK_PATCH_MEMBER_RENAMED("usedTransformSets", "old_usedTransformSets")
		HK_PATCH_MEMBER_ADDED("usedTransformSets", TYPE_ARRAY_STRUCT, "hclClothStateTransformSetAccess", 0)
		HK_PATCH_FUNCTION(hclClothState_0_to_1)
        HK_PATCH_MEMBER_REMOVED("old_usedTransformSets", TYPE_ARRAY_INT, HK_NULL, 0)
        HK_PATCH_DEPENDS("hclClothStateTransformSetAccess", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSkinOperator", 3, "hclSkinOperator", 4)
		HK_PATCH_MEMBER_ADDED("dualQuaternionSkinning", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN(HK_NULL, HK_CLASS_ADDED, "hclConvexGeometryShape", 0)
	HK_PATCH_PARENT_SET(HK_NULL, "hclShape")
	HK_PATCH_MEMBER_ADDED("tetrahedraGrid", TYPE_ARRAY_INT, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("gridCells", TYPE_ARRAY_BYTE, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("tetrahedraEquations", TYPE_ARRAY_VEC_16, HK_NULL,0)
	HK_PATCH_MEMBER_ADDED("objAabb", TYPE_STRUCT, "hkAabb", 0)
	HK_PATCH_MEMBER_ADDED("localFromWorld", TYPE_VEC_16, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("worldFromLocal", TYPE_VEC_16, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("geomCentroid", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("invCellSize", TYPE_VEC_4, HK_NULL, 0)
	HK_PATCH_MEMBER_ADDED("gridRes", TYPE_INT, HK_NULL, 0)
	HK_PATCH_DEPENDS("hclShape", 0)
	HK_PATCH_DEPENDS("hkBaseObject", 0)
	HK_PATCH_DEPENDS("hkAabb", 0)
	HK_PATCH_DEPENDS("hkReferencedObject", 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSkinSetupObject", 0, "hclSkinSetupObject", 1)
		HK_PATCH_MEMBER_ADDED("useDualQuaternionMethod", TYPE_BYTE, HK_NULL, 0)
HK_PATCH_END()

HK_PATCH_BEGIN("hclSkinOperatorBoneInfluence", 1, "hclSkinOperatorBoneInfluence", 2)
		HK_PATCH_MEMBER_RENAMED("boneIndex", "old_boneIndex")
		HK_PATCH_MEMBER_ADDED("boneIndex", TYPE_BYTE, HK_NULL, 0)
		HK_PATCH_FUNCTION(hclSkinOperatorBoneInfluence_1_to_2)
		HK_PATCH_MEMBER_REMOVED("old_boneIndex", TYPE_INT, HK_NULL, 0)
HK_PATCH_END()

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20130718)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
