/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

#include "Reflections/hkxAnimatedQuaternionReflection.cpp"
#include "Reflections/hkxAnimatedMatrixReflection.cpp"
#include "Reflections/hkxTriangleSelectionChannelReflection.cpp"
#include "Reflections/hkxVertexIntDataChannelReflection.cpp"
#include "Reflections/hkxVertexDescriptionReflection.cpp"
#include "Reflections/hkxVertexBufferReflection.cpp"
#include "Reflections/hkxMaterialReflection.cpp"
#include "Reflections/hkxLightReflection.cpp"
#include "Reflections/hkxMaterialShaderSetReflection.cpp"
#include "Reflections/hkxAnimatedVectorReflection.cpp"
#include "Reflections/hkxMeshReflection.cpp"
#include "Reflections/hkxVertexSelectionChannelReflection.cpp"
#include "Reflections/hkxSparselyAnimatedBoolReflection.cpp"
#include "Reflections/hkxVertexFloatDataChannelReflection.cpp"
#include "Reflections/hkxVertexAnimationReflection.cpp"
#include "Reflections/hkxAttributeGroupReflection.cpp"
#include "Reflections/hkxIndexBufferReflection.cpp"
#include "Reflections/hkxTextureFileReflection.cpp"
#include "Reflections/hkxAttributeReflection.cpp"
#include "Reflections/hkxNodeSelectionSetReflection.cpp"
#include "Reflections/hkxCameraReflection.cpp"
#include "Reflections/hkxSparselyAnimatedIntReflection.cpp"
#include "Reflections/hkxAttributeHolderReflection.cpp"
#include "Reflections/hkxNodeReflection.cpp"
#include "Reflections/hkxBlobMeshShapeReflection.cpp"
#include "Reflections/hkxMeshSectionReflection.cpp"
#include "Reflections/hkxMaterialEffectReflection.cpp"
#include "Reflections/hkxSplineReflection.cpp"
#include "Reflections/hkxSparselyAnimatedEnumReflection.cpp"
#include "Reflections/hkxSkinBindingReflection.cpp"
#include "Reflections/hkxMaterialShaderReflection.cpp"
#include "Reflections/hkxAnimatedFloatReflection.cpp"
#include "Reflections/hkxSparselyAnimatedStringReflection.cpp"
#include "Reflections/hkxEdgeSelectionChannelReflection.cpp"
#include "Reflections/hkxTextureInplaceReflection.cpp"
#include "Reflections/hkxVertexVectorDataChannelReflection.cpp"
#include "Reflections/hkAlignSceneToNodeOptionsReflection.cpp"
#include "Reflections/hkxEnvironmentReflection.cpp"
#include "Reflections/hkxBlobReflection.cpp"
#include "Reflections/hkxSceneReflection.cpp"

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20130718)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
