/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

#include "Reflections/hkpMotorActionReflection.cpp"
#include "Reflections/hkpPhysicsDataReflection.cpp"
#include "Reflections/hkpDashpotActionReflection.cpp"
#include "Reflections/hkpCharacterProxyCinfoReflection.cpp"
#include "Reflections/hkpFirstPersonGunReflection.cpp"
#include "Reflections/hkpAngularDashpotActionReflection.cpp"
#include "Reflections/hkpGravityGunReflection.cpp"
#include "Reflections/hkpSpringActionReflection.cpp"
#include "Reflections/hkpDisableEntityCollisionFilterReflection.cpp"
#include "Reflections/hkpPhysicsSystemWithContactsReflection.cpp"
#include "Reflections/hkpGroupCollisionFilterReflection.cpp"
#include "Reflections/hkpTriggerVolumeReflection.cpp"
#include "Reflections/hkpMouseSpringActionReflection.cpp"
#include "Reflections/hkpSerializedDisplayMarkerReflection.cpp"
#include "Reflections/hkpSerializedDisplayRbTransformsReflection.cpp"
#include "Reflections/hkpBallGunReflection.cpp"
#include "Reflections/hkpCharacterControllerCinfoReflection.cpp"
#include "Reflections/hkpSerializedDisplayMarkerListReflection.cpp"
#include "Reflections/hkpConstrainedSystemFilterReflection.cpp"
#include "Reflections/hkpDisplayBindingDataReflection.cpp"
#include "Reflections/hkpPoweredChainMapperReflection.cpp"
#include "Reflections/hkpCharacterRigidBodyCinfoReflection.cpp"
#include "Reflections/hkpMountedBallGunReflection.cpp"
#include "Reflections/hkpSerializedAgentNnEntryReflection.cpp"
#include "Reflections/hkpProjectileGunReflection.cpp"
#include "Reflections/hkpReorientActionReflection.cpp"

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20130718)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
