/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (projectClassList.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

#include "Reflections/hkpRayCollidableFilterReflection.cpp"
#include "Reflections/hkpMultiRayShapeReflection.cpp"
#include "Reflections/hkpSphereShapeReflection.cpp"
#include "Reflections/hkpCollidableReflection.cpp"
#include "Reflections/hkpCdBodyReflection.cpp"
#include "Reflections/hkpWeldingUtilityReflection.cpp"
#include "Reflections/hkpCollidableCollidableFilterReflection.cpp"
#include "Reflections/hkpNamedMeshMaterialReflection.cpp"
#include "Reflections/hkpShapeContainerReflection.cpp"
#include "Reflections/hkpConvexListShapeReflection.cpp"
#include "Reflections/hkpTransformShapeReflection.cpp"
#include "Reflections/hkpListShapeReflection.cpp"
#include "Reflections/hkpConvexShapeReflection.cpp"
#include "Reflections/hkpPhantomCallbackShapeReflection.cpp"
#include "Reflections/hkpRemoveTerminalsMoppModifierReflection.cpp"
#include "Reflections/hkpMeshMaterialReflection.cpp"
#include "Reflections/hkpNullCollisionFilterReflection.cpp"
#include "Reflections/hkpGroupFilterReflection.cpp"
#include "Reflections/hkpShapeBaseReflection.cpp"
#include "Reflections/hkpBvTreeShapeReflection.cpp"
#include "Reflections/hkpDefaultConvexListFilterReflection.cpp"
#include "Reflections/hkpShapeReflection.cpp"
#include "Reflections/hkpConvexTranslateShapeReflection.cpp"
#include "Reflections/hkpMultiSphereShapeReflection.cpp"
#include "Reflections/hkpCollisionFilterListReflection.cpp"
#include "Reflections/hkpConvexTransformShapeReflection.cpp"
#include "Reflections/hkpTriangleShapeReflection.cpp"
#include "Reflections/hkpConvexVerticesShapeReflection.cpp"
#include "Reflections/hkpCylinderShapeReflection.cpp"
#include "Reflections/hkpSphereRepShapeReflection.cpp"
#include "Reflections/hkpConvexVerticesConnectivityReflection.cpp"
#include "Reflections/hkpBoxShapeReflection.cpp"
#include "Reflections/hkpConvexListFilterReflection.cpp"
#include "Reflections/hkpLinkedCollidableReflection.cpp"
#include "Reflections/hkpRayShapeCollectionFilterReflection.cpp"
#include "Reflections/hkpShapeInfoReflection.cpp"
#include "Reflections/hkpTypedBroadPhaseHandleReflection.cpp"
#include "Reflections/hkpAgent1nTrackReflection.cpp"
#include "Reflections/hkpMoppBvTreeShapeReflection.cpp"
#include "Reflections/hkpShapeCollectionFilterReflection.cpp"
#include "Reflections/hkpBvShapeReflection.cpp"
#include "Reflections/hkpCapsuleShapeReflection.cpp"
#include "Reflections/hkpCollisionFilterReflection.cpp"
#include "Reflections/hkpShapeCollectionReflection.cpp"
#include "Reflections/hkpBroadPhaseHandleReflection.cpp"
#ifndef HK_EXCLUDE_FEATURE_hkpCompressedMeshShape
#include "Reflections/hkpCompressedMeshShapehkpCompressedMeshShapeReflection.cpp"
#endif
#ifndef HK_EXCLUDE_FEATURE_hkpConvexPieceMeshShape
#include "Reflections/hkpConvexPieceMeshShapehkpConvexPieceMeshShapeReflection.cpp"
#endif
#ifndef HK_EXCLUDE_FEATURE_hkpExtendedMeshShape
#include "Reflections/hkpExtendedMeshShapehkpStorageExtendedMeshShapeReflection.cpp"
#include "Reflections/hkpExtendedMeshShapehkpExtendedMeshShapeReflection.cpp"
#endif
#ifndef HK_EXCLUDE_FEATURE_hkpHeightField
#include "Reflections/hkpHeightFieldhkpPlaneShapeReflection.cpp"
#include "Reflections/hkpHeightFieldhkpHeightFieldShapeReflection.cpp"
#include "Reflections/hkpHeightFieldhkpTriSampledHeightFieldBvTreeShapeReflection.cpp"
#include "Reflections/hkpHeightFieldhkpSampledHeightFieldShapeReflection.cpp"
#include "Reflections/hkpHeightFieldhkpTriSampledHeightFieldCollectionReflection.cpp"
#include "Reflections/hkpHeightFieldhkpStorageSampledHeightFieldShapeReflection.cpp"
#include "Reflections/hkpHeightFieldhkpCompressedSampledHeightFieldShapeReflection.cpp"
#endif
#ifndef HK_EXCLUDE_FEATURE_hkpMeshShape
#include "Reflections/hkpMeshShapehkpMeshShapeReflection.cpp"
#include "Reflections/hkpMeshShapehkpStorageMeshShapeReflection.cpp"
#include "Reflections/hkpMeshShapehkpFastMeshShapeReflection.cpp"
#endif
#ifndef HK_EXCLUDE_FEATURE_hkpSimpleMeshShape
#include "Reflections/hkpSimpleMeshShapehkpSimpleMeshShapeReflection.cpp"
#endif

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20130718)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
