/*
 *
 * Confidential Information of Telekinesys Research Limited (t/a Havok). Not for disclosure or distribution without Havok's
 * prior written consent. This software contains code, techniques and know-how which is confidential and proprietary to Havok.
 * Product and Trade Secret source code contains trade secrets of Havok. Havok Software (C) Copyright 1999-2013 Telekinesys Research Limited t/a Havok. All Rights Reserved. Use of this software is subject to the terms of an end user license agreement.
 *
 */

//HK_REFLECTION_PARSER_EXCLUDE_FILE

// Autogenerated by generateReflections.py (reflectedClasses.py)
// Changes will not be lost unless:
// - The workspace is re-generated using build.py
// - The corresponding reflection database (reflection.db) is deleted
// - The --force-output or --force-rebuild option is added to the pre-build generateReflection.py execution

// Generated from 'ContentTools/Common/Filters/FilterTutorial/ConvertToPhantomAction/hctConvertToPhantomActionOptions.h'
#include <ContentTools/Common/Filters/FilterTutorial/hctFilterTutorial.h>
#include <Common/Base/Reflection/hkClass.h>
#include <Common/Base/Reflection/hkInternalClassMember.h>
#include <Common/Base/Reflection/hkTypeInfo.h>
#include <Common/Base/Reflection/Attributes/hkAttributes.h>
#include <ContentTools/Common/Filters/FilterTutorial/ConvertToPhantomAction/hctConvertToPhantomActionOptions.h>
#define True true
#define False false


//
// Class hctConvertToPhantomActionOptions
//
static const hkInternalClassMember hctConvertToPhantomActionOptionsClass_Members[] =
{
	{ "removeMeshes", HK_NULL, HK_NULL, hkClassMember::TYPE_BOOL, hkClassMember::TYPE_VOID, 0, 0, HK_OFFSET_OF(hctConvertToPhantomActionOptions,m_removeMeshes), HK_NULL }
};
extern const hkClass hctConvertToPhantomActionOptionsClass;
const hkClass hctConvertToPhantomActionOptionsClass(
	"hctConvertToPhantomActionOptions",
	HK_NULL, // parent
	sizeof(::hctConvertToPhantomActionOptions),
	HK_NULL,
	0, // interfaces
	HK_NULL,
	0, // enums
	reinterpret_cast<const hkClassMember*>(hctConvertToPhantomActionOptionsClass_Members),
	HK_COUNT_OF(hctConvertToPhantomActionOptionsClass_Members),
	HK_NULL, // defaults
	HK_NULL, // attributes
	0, // flags
	hkUint32(0) // version
	);
#ifndef HK_HKCLASS_DEFINITION_ONLY
const hkClass& HK_CALL hctConvertToPhantomActionOptions::staticClass()
{
	return hctConvertToPhantomActionOptionsClass;
}
HK_COMPILE_TIME_ASSERT2( \
	sizeof(hkIsVirtual(static_cast<hctConvertToPhantomActionOptions*>(0))) == sizeof(hkBool::CompileTimeFalseType), \
	REFLECTION_PARSER_VTABLE_DETECTION_FAILED );
static void HK_CALL cleanupLoadedObjecthctConvertToPhantomActionOptions(void* p)
{
	static_cast<hctConvertToPhantomActionOptions*>(p)->~hctConvertToPhantomActionOptions();
}
extern const hkTypeInfo hctConvertToPhantomActionOptionsTypeInfo;
const hkTypeInfo hctConvertToPhantomActionOptionsTypeInfo(
	"hctConvertToPhantomActionOptions",
	"!hctConvertToPhantomActionOptions",
	HK_NULL,
	cleanupLoadedObjecthctConvertToPhantomActionOptions,
	HK_NULL,
	sizeof(hctConvertToPhantomActionOptions)
	);
#endif

/*
 * Havok SDK - NO SOURCE PC DOWNLOAD, BUILD(#20130718)
 * 
 * Confidential Information of Havok.  (C) Copyright 1999-2013
 * Telekinesys Research Limited t/a Havok. All Rights Reserved. The Havok
 * Logo, and the Havok buzzsaw logo are trademarks of Havok.  Title, ownership
 * rights, and intellectual property rights in the Havok software remain in
 * Havok and/or its suppliers.
 * 
 * Use of this software for evaluation purposes is subject to and indicates
 * acceptance of the End User licence Agreement for this product. A copy of
 * the license is included with this software and is also available at www.havok.com/tryhavok.
 * 
 */
